{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<img style=\"float:left\" width=\"70%\" src=\"escudo_COLOR_1L_DCHA.png\">\n",
    "<img style=\"float:right\" width=\"15%\" src=\"PythonLogo.svg\">\n",
    "<br style=\"clear:both;\">\n",
    "\n",
    "\n",
    "# **Juego Linja**\n",
    "### *Sistemas Inteligentes* (Curso 2023-2024)\n",
    "\n",
    "\n",
    "***Alumna:** Jimena Arnaiz González*"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**NOTA:** En algún método hay prints interesantes como el de \"fila ocupada\" del método obtenerMov() o \"turno perdido\" de extraPerdida() comentados para que no se repitan a la hora de usar el minimax (jugada del jugador2).\n",
    "Hice eso porque no encontré una forma de hacer que no se me repitieran. También, respecto a este tema, hay dos métodos que están repetidos (un método con prints y otro sin prints) para evitar esa repetición. En esos dos, repito el código en vez de comentar los print directamente porque tienen varios prints que podrían servir de ayuda a la hora de realizar el movimiento en el jugador1. "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Clase TableroLinja** "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from copy import deepcopy\n",
    "from typing import Tuple, List\n",
    "import math\n",
    "\n",
    "#librerías para mostrar el tablero con imgs\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.image as mpimg\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "class TableroLinja:\n",
    "    '''\n",
    "    Constructor de la clase TableroLinja.\n",
    "\n",
    "    @param matrix: Matriz que representa el estado inicial del tablero.\n",
    "    ''' \n",
    "    def __init__(self, matrix):\n",
    "        self.setMatrix(matrix)\n",
    "        self.fil = len(matrix)\n",
    "        self.col = len(matrix[0])\n",
    "        self.turno = 1 #turno actual\n",
    "        self.contMovs = 2\n",
    "        self.turnoExtra = False\n",
    "        self.filas2Mov = 0 #filas que puedes saltar en el movimiento 2\n",
    "    \n",
    "    '''\n",
    "    Comprueba si dos instancias de TableroLinja son iguales.\n",
    "\n",
    "    @param other: Otra instancia de TableroLinja para comparar.\n",
    "    @return: True si las instancias son iguales, False en caso contrario.\n",
    "    '''\n",
    "    def __eq__(self, other) -> bool:\n",
    "        for i in range(self.fil):\n",
    "            for j in range(self.col):\n",
    "                if self.matrix[i][j] != other.matrix[i][j]:\n",
    "                    return False\n",
    "        return True\n",
    "    \n",
    "    '''\n",
    "    Establece la matriz del objeto actual con una copia profunda de la matriz proporcionada.\n",
    "\n",
    "    @param matrix: Nueva matriz para asignar al tablero.\n",
    "    '''\n",
    "    def setMatrix(self, matrix):\n",
    "        self.matrix = deepcopy(matrix)\n",
    "    \n",
    "    '''\n",
    "    Devuelve una copia profunda de la matriz almacenada en el objeto actual.\n",
    "\n",
    "    @return: Copia profunda de la matriz.\n",
    "    '''\n",
    "    def getMatrix(self) -> List[List]:\n",
    "        return deepcopy(self.matrix)\n",
    "    \n",
    "    '''\n",
    "    Copia los atributos del tablero pasado por parámetro en el tablero actual.\n",
    "    La utilizo para realizar en el minimax la copia de los estados hijos.\n",
    "\n",
    "    @param other: Otra instancia de TableroLinja para copiar sus atributos.\n",
    "    '''\n",
    "    def copyFrom(self, other):\n",
    "        # Copy the state of another TableroLinja object to this object.\n",
    "        self.fil = other.fil\n",
    "        self.col = other.col\n",
    "        self.turno = other.turno\n",
    "        self.contMovs = other.contMovs\n",
    "        self.turnoExtra = other.turnoExtra\n",
    "        self.filas2Mov = other.filas2Mov\n",
    "        \n",
    "    '''\n",
    "    Imprime el tablero con letras.\n",
    "\n",
    "    @return: Representación en cadena del tablero.\n",
    "    '''\n",
    "    def imprimirTablero(self):\n",
    "        result = \"\"\n",
    "        result += '\\n'\n",
    "        for i in range(len(self.matrix)):\n",
    "            for j in range(len(self.matrix[0])):\n",
    "                result += str(self.matrix[i][j]) + ' '\n",
    "            result += '\\n'\n",
    "        return result #hago que retorne el resultado pq de otra forma imprimía None siempre\n",
    "    \n",
    "    '''\n",
    "    Impresión del tablero con imágenes.\n",
    "    Utiliza un diccionario que mapea valores en el tablero a nombres de archivos de imagen.\n",
    "    \n",
    "    @return: No debería de retornar nada, pero al llamarlo, me muestra None \n",
    "    '''\n",
    "    def imprimirTabConImagenes(self):\n",
    "        #Diccionario que mapea valores en el tablero a nombres de archivos de imagen\n",
    "        imagen_dict = {'R': 'rojaBienBorde.jpg', 'V': 'vacioBienBorde.jpg', 'N': 'negraBienBorde.jpg'}\n",
    "        \n",
    "        # Crea una figura y ejes\n",
    "        fig, ax = plt.subplots()\n",
    "\n",
    "        matriz = np.array(self.getMatrix())\n",
    "\n",
    "        #Configura el tamaño de la figura para que coincida con el tamaño de la matriz\n",
    "        fig.set_size_inches(np.array(matriz.shape[::-1]) / 2)\n",
    "\n",
    "        #Itera sobre la matriz y mostrar imágenes según los valores en el tablero\n",
    "        for i in range(matriz.shape[0]):\n",
    "            for j in range(matriz.shape[1]):\n",
    "                if matriz[i, j] in imagen_dict:\n",
    "                    imagen = mpimg.imread(imagen_dict[matriz[i, j]])\n",
    "                    ax.imshow(imagen, extent=(j, j + 1, matriz.shape[0] - i - 1, matriz.shape[0] - i))\n",
    "\n",
    "        #Dibuja líneas para separar las celdas en el borde derecho e inferior\n",
    "        for i in range(matriz.shape[0]):\n",
    "            ax.add_line(plt.Line2D([matriz.shape[1], matriz.shape[1]], [i, i + 1], color='black'))\n",
    "        for j in range(matriz.shape[1]):\n",
    "            ax.add_line(plt.Line2D([j, j + 1], [matriz.shape[0], matriz.shape[0]], color='black'))\n",
    "            \n",
    "        # Dibuja líneas para separar las celdas en el borde derecho e inferior\n",
    "        for i in range(matriz.shape[0]):\n",
    "            ax.add_line(plt.Line2D([matriz.shape[1], matriz.shape[1]], [i, i + 1], color='black'))\n",
    "            ax.add_line(plt.Line2D([0, matriz.shape[1]], [i + 1, i + 1], color='black'))\n",
    "\n",
    "        for j in range(matriz.shape[1]):\n",
    "            ax.add_line(plt.Line2D([j, j + 1], [matriz.shape[0], matriz.shape[0]], color='black'))\n",
    "            ax.add_line(plt.Line2D([j, j], [0, matriz.shape[0]], color='black'))\n",
    "        \n",
    "         # Dibuja líneas para los bordes exteriores\n",
    "        ax.add_line(plt.Line2D([0, matriz.shape[1]], [0, 0], color='black'))\n",
    "        ax.add_line(plt.Line2D([matriz.shape[1], matriz.shape[1]], [0, matriz.shape[0]], color='black'))\n",
    "        ax.add_line(plt.Line2D([0, 0], [0, matriz.shape[0]], color='black'))\n",
    "        ax.add_line(plt.Line2D([0, matriz.shape[1]], [matriz.shape[0], matriz.shape[0]], color='black'))\n",
    "\n",
    "        #Configura ejes y muestra la figura\n",
    "        ax.set_xlim(0, matriz.shape[1])\n",
    "        ax.set_ylim(0, matriz.shape[0])\n",
    "        ax.set_aspect('equal', 'box')\n",
    "        ax.axis('off')\n",
    "        \n",
    "        plt.show()\n",
    "\n",
    "                \n",
    "    '''\n",
    "    Dada una fila y columna, coloca la pieza (tile) en dicha posición.\n",
    "\n",
    "    @param fila: Fila de la posición.\n",
    "    @param col: Columna de la posición.\n",
    "    @param tile: Valor a colocar en la posición.\n",
    "    '''\n",
    "    def placeTile(self, fila: int, col: int, tile: int):\n",
    "        if 0 <= fila < self.fil and 0 <= col < self.col:\n",
    "            self.matrix[fila][col] = tile\n",
    "    \n",
    "    '''\n",
    "    Elimina el elemento de la posición especificada.\n",
    "\n",
    "    @param fila: Fila de la posición a eliminar.\n",
    "    @param col: Columna de la posición a eliminar.\n",
    "    '''\n",
    "    def deleteTile(self, fila: int, col: int):\n",
    "        if (0 <= fila < self.fil) and (0 <= col < self.col): \n",
    "            self.matrix[fila][col] = 'V'\n",
    "    \n",
    "    '''\n",
    "    Devuelve la celda correspondiente a la fila y columna pasadas por parámetro.\n",
    "\n",
    "    @param fila: Fila de la celda.\n",
    "    @param col: Columna de la celda.\n",
    "    @return: Valor de la celda.\n",
    "    '''\n",
    "    def getCelda(self, fila: int, col: int):\n",
    "        return self.matrix[fila][col]\n",
    "    \n",
    "    '''\n",
    "    Devuelve las filas a las que puedes ir (no completas).\n",
    "\n",
    "    @return: Lista de filas accesibles.\n",
    "    '''\n",
    "    def isAvailable(self) -> list:\n",
    "        filasAccesibles = []\n",
    "        \n",
    "        filasAccesibles.append(self.matrix[0]) #Agregar la fila 0 (pq puede haber un nº indef de fichas en los extremos)\n",
    "\n",
    "        for i in range(self.fil):\n",
    "            for j in range(self.col):\n",
    "                if 'V' in self.matrix[i]:  # Si encuentra al menos una 'V' en la fila, agrega la fila\n",
    "                    filasAccesibles.append(self.matrix[i])\n",
    "                    break\n",
    "        filasAccesibles.append(self.matrix[7]) #Agregar la fila 7 (extremo del j1)\n",
    "\n",
    "        return filasAccesibles\n",
    "    \n",
    "    '''\n",
    "    Función de coste minimax (una función para fichas rojas y otra para negras).\n",
    "\n",
    "    @param jugador: Jugador para el cual se calcula el coste (1 para fichas rojas, 2 para fichas negras).\n",
    "    @return: Valor del coste minimax.\n",
    "    '''\n",
    "    def utility(self, jugador: int) -> int:\n",
    "        puntosR = 0\n",
    "        puntosN = 0\n",
    "        puntos_valores = [5, 3, 2, 1, -1, -2, -3, -5]\n",
    "\n",
    "        for i in range(len(self.matrix)):\n",
    "            for j in range(self.col):\n",
    "                if self.matrix[i][j] == 'R':\n",
    "                    puntosR += puntos_valores[i]\n",
    "                elif self.matrix[i][j] == 'N':\n",
    "                    puntosN -= puntos_valores[i]\n",
    "        if jugador == 1:\n",
    "            return puntosR - puntosN\n",
    "        else:\n",
    "            return puntosN - puntosR\n",
    "    \n",
    "    '''\n",
    "    Halla los puntos del jugador pasado por parámetro.\n",
    "\n",
    "    @param jugador: Jugador para el cual se calcula el puntaje (1 para fichas rojas, 2 para fichas negras).\n",
    "    @return: Puntaje del jugador.\n",
    "    '''\n",
    "    def puntuaje(self, jugador: int) -> int:\n",
    "        puntosR = 0\n",
    "        puntosN = 0\n",
    "        puntos_valores = [5, 3, 2, 1, -1, -2, -3, -5]\n",
    "\n",
    "        for i in range(len(self.matrix)):\n",
    "            for j in range(self.col):\n",
    "                if self.matrix[i][j] == 'R':\n",
    "                    puntosR += puntos_valores[i]\n",
    "                elif self.matrix[i][j] == 'N':\n",
    "                    puntosN -= puntos_valores[i]\n",
    "        if jugador == 1:\n",
    "            return puntosR\n",
    "        return puntosN\n",
    "    \n",
    "    '''\n",
    "    Valida si la fila pasada por parámetro está dentro de los límites del tablero.\n",
    "\n",
    "    @param row: Fila a validar.\n",
    "    @return: True si la fila es válida, False en caso contrario.\n",
    "    '''\n",
    "    def filaValida(self, row: int):\n",
    "        if row < self.fil and row >= 0:\n",
    "            return True\n",
    "        return print(\"\\n\\033[1;91mFila fuera de los límites del tablero\\033[0m\")\n",
    "    \n",
    "    '''\n",
    "    Valida si la columna pasada por parámetro está dentro de los límites del tablero.\n",
    "\n",
    "    @param col: Columna a validar.\n",
    "    @return: True si la columna es válida, False en caso contrario.\n",
    "    '''\n",
    "    def colValida(self, col: int):\n",
    "        if col < self.col and col >= 0:\n",
    "            return True\n",
    "        return print(\"\\n\\033[1;91mColumna fuera de los límites del tablero\\033[0m\")\n",
    "    \n",
    "    '''\n",
    "    Retorna True si la fila pasada por parámetro está vacía (todos los elementos son 'V').\n",
    "\n",
    "    @param row: Fila a verificar.\n",
    "    @return: True si la fila está vacía, False en caso contrario.\n",
    "    '''\n",
    "    def filaVacia(self, row: int) -> bool:\n",
    "        for j in range(len(self.matrix[row])):\n",
    "            if self.matrix[row][j] != 'V':\n",
    "                return False\n",
    "        return True\n",
    "    \n",
    "    '''\n",
    "    Dada una fila, devuelve una lista con las columnas que contienen elementos 'V' (celdas vacías).\n",
    "\n",
    "    @param row: Fila a analizar.\n",
    "    @return: Lista de columnas con celdas vacías.\n",
    "    '''\n",
    "    def celdasVacias(self, row):  \n",
    "        celdas = []\n",
    "        for j in range(len(self.matrix[row])): #todas las vacías de una fila\n",
    "            if self.matrix[row][j] == 'V':\n",
    "                celdas.append(j)\n",
    "        return celdas\n",
    "             \n",
    "    '''\n",
    "    Devuelve en qué movimiento se encuentra el jugador (1 para el primer movimiento, 2 para el segundo movimiento).\n",
    "\n",
    "    @return: Número del movimiento actual.\n",
    "    '''\n",
    "    def queMovEs(self):\n",
    "        if self.contMovs == 2: # si me quedan 2 movs, estoy en mi 1er mov\n",
    "            return 1\n",
    "        else:\n",
    "            return 2\n",
    "\n",
    "    '''\n",
    "    Valida si se puede realizar el movimiento especificado.\n",
    "\n",
    "    @param fila: Fila de origen del movimiento.\n",
    "    @param col: Columna de origen del movimiento.\n",
    "    @param nCol: Nueva columna de destino del movimiento.\n",
    "    @return: True si el movimiento es válido, False en caso contrario.\n",
    "    '''\n",
    "    def validarMov (self, fila: int, col: int, nCol: int):\n",
    "        celda = self.getCelda(fila,col)\n",
    "        valid = True  \n",
    "\n",
    "        if not self.filaValida(fila) or not self.colValida(col):\n",
    "            ##print(\"La posición está fuera de los límites del tablero\")\n",
    "            valid = False\n",
    "        if self.turno == 1 and celda != 'R':\n",
    "            ##print(f\"El jugador {self.turno} debe jugar con fichas rojas\")\n",
    "            valid = False\n",
    "\n",
    "        elif self.turno == 2 and celda != 'N':\n",
    "            ##print(f\"El jugador {self.turno} debe jugar con fichas negras\")\n",
    "            valid = False\n",
    "\n",
    "        return valid\n",
    "    \n",
    "    \n",
    "    #valida si se puede hacer el movimiento \n",
    "    #igual que la anterior, pero con prints\n",
    "    def validarMovConPrints (self, fila: int, col: int, nCol: int):\n",
    "        celda = self.getCelda(fila,col)\n",
    "        valid = True  \n",
    "\n",
    "        if not self.filaValida(fila) or not self.colValida(col):\n",
    "            print(\"\\033[1;91mLa posición está fuera de los límites del tablero\\033[0m\")\n",
    "            valid = False\n",
    "        if self.turno == 1 and celda != 'R':\n",
    "            print(f\"\\033[1;91mEl jugador {self.turno} debe jugar con fichas rojas\\033[0m\")\n",
    "            valid = False\n",
    "\n",
    "        elif self.turno == 2 and celda != 'N':\n",
    "            print(f\"\\033[1;91mEl jugador {self.turno} debe jugar con fichas negras\\033[0m\")\n",
    "            valid = False\n",
    "\n",
    "        return valid\n",
    "    \n",
    "    '''\n",
    "    Método auxiliar creado para saber en minimax si el movimiento se puede realizar.\n",
    "\n",
    "    @param row: Fila de origen del movimiento.\n",
    "    @param col: Columna de origen del movimiento.\n",
    "    @param nCol: Nueva columna de destino del movimiento.\n",
    "    @return: True si el movimiento es posible, False en caso contrario.\n",
    "    '''\n",
    "    def puedoHacerMov(self, row: int, col: int, nCol: int) :\n",
    "        ficha = self.getCelda(row, col)\n",
    "        if self.turno == 1: #la ficha es dif para cada jugador\n",
    "            ficha = 'R'\n",
    "        else:\n",
    "            ficha = 'N'\n",
    "            \n",
    "        if self.contMovs == 2: # si me quedan 2 movs, estoy en mi 1er mov\n",
    "            numMov = 1\n",
    "        else:\n",
    "            numMov = 2\n",
    "            \n",
    "        #obtengo la jugada \n",
    "        jugada = self.obtenerMov(row, col, self.turno, numMov)\n",
    "        \n",
    "        if len(jugada) != 2:\n",
    "            ##print(\"No se encontró una jugada válida para el movimiento inicial.\")\n",
    "            return False\n",
    "        #pos final ficha\n",
    "        nRow = jugada[1][0]\n",
    "\n",
    "        #jugada\n",
    "        if self.getCelda(nRow, nCol) == 'V': # si está libre se hace el mov\n",
    "            return True\n",
    "        else:\n",
    "            ##print(\"La celda no está libre\")\n",
    "            return False\n",
    "        \n",
    "        return \n",
    "    \n",
    "    \n",
    "    '''mismo método que el anterior, pero con prints para que le salgan al jugador físico\n",
    "       ya que en el minimax si dejo los prints, me salen muchas veces por las iteraciones\n",
    "    '''\n",
    "    def puedoHacerMovConPrints(self, row: int, col: int, nCol: int) :\n",
    "        ficha = self.getCelda(row, col)\n",
    "        if self.turno == 1: #la ficha es dif para cada jugador\n",
    "            ficha = 'R'\n",
    "        else:\n",
    "            ficha = 'N'\n",
    "            \n",
    "        if self.contMovs == 2: # si me quedan 2 movs, estoy en mi 1er mov\n",
    "            numMov = 1\n",
    "        else:\n",
    "            numMov = 2\n",
    "            \n",
    "        #obtengo la jugada \n",
    "        jugada = self.obtenerMov(row, col, self.turno, numMov)\n",
    "        \n",
    "        if len(jugada) != 2:\n",
    "            print(\"\\033[1;91mNo se encontró una jugada válida para el movimiento.\\033[0m\")\n",
    "            return False\n",
    "        #pos final ficha\n",
    "        nRow = jugada[1][0]\n",
    "\n",
    "        #jugada\n",
    "        if self.getCelda(nRow, nCol) == 'V': # si está libre se hace el mov\n",
    "            return True\n",
    "        else:\n",
    "            print(\"\\033[1;91mLa celda de destino no está libre\\033[0m\")\n",
    "            return False\n",
    "        \n",
    "        return \n",
    "           \n",
    "        \n",
    "    '''\n",
    "    Prevé cuál es el primer movimiento que me da un segundo movimiento con un mayor número de casillas.\n",
    "    Método que me devuelve un número entero correspondiente a dicho número.\n",
    "\n",
    "    @param row: Fila sobre la que quiero saber las celdas ocupadas.\n",
    "    @return: Número correspondiente al número de casillas ocupadas de dicha fila.\n",
    "    '''\n",
    "    def numMovs(self, row: int) -> int:\n",
    "        cont = 0  \n",
    "        if 0 <= row < len(self.matrix):\n",
    "            for j in range(len(self.matrix[row])):\n",
    "                if 0 <= j < len(self.matrix[row]): #Asegura los límites del índice de la columna\n",
    "                    if self.matrix[row][j] != 'V':\n",
    "                        cont += 1\n",
    "        return cont\n",
    "        \n",
    "    '''\n",
    "    Indica la posición de la ficha que se mueve y hacia dónde se mueve (fila de destino).\n",
    "\n",
    "    @param row: Fila de origen.\n",
    "    @param col: Columna de origen.\n",
    "    @param playerID: Jugador.\n",
    "    @param numMov: Número de movimiento actual.\n",
    "    @return: Lista que indica la posición de la ficha que se mueve y hacia dónde se mueve.\n",
    "    '''\n",
    "    def obtenerMov(self, row: int, col: int, playerID: int, numMov:int) -> List[List]:\n",
    "        mov = []\n",
    "              \n",
    "        if numMov == 1: #si está en el 1er mov\n",
    "            if playerID == 1: #R\n",
    "                newRow = row - 1 #avanza una fila arriba\n",
    "            else: #N\n",
    "                newRow = row + 1 #avanza una fila abajo\n",
    "            self.filas2Mov = self.numMovs(newRow)\n",
    "            \n",
    "            if newRow == 7 or newRow == 0:\n",
    "                self.filas2Mov = 1\n",
    "        \n",
    "        if numMov == 2:\n",
    "            if playerID == 1: #R\n",
    "                newRow = row - self.filas2Mov\n",
    "            else:\n",
    "                newRow = row + self.filas2Mov\n",
    "                \n",
    "        #control de extremos        \n",
    "        if newRow > 7:\n",
    "            newRow = 7\n",
    "        elif newRow < 0:\n",
    "            newRow = 0 \n",
    "            \n",
    "        if self.matrix[newRow] in self.isAvailable(): #compruebo si la fila no está ocupada\n",
    "                mov.append([row, col])\n",
    "                mov.append([newRow])\n",
    "        ##else:\n",
    "            ##print(\"La fila está ocupada\") si no comento el print, se me repite por el minimax\n",
    "        return mov \n",
    "    \n",
    "    \n",
    "    #Cambia el turno\n",
    "    def cambiarTurno(self):\n",
    "        if self.turno == 1:\n",
    "            self.turno = 2\n",
    "        else:\n",
    "            self.turno = 1\n",
    "      \n",
    "    '''\n",
    "    Mueve una ficha (realiza un movimiento)\n",
    "\n",
    "    @param row: Fila de origen.\n",
    "    @param col: Columna de origen.\n",
    "    @param nCol: Columna de destino.\n",
    "    @return: \n",
    "    '''\n",
    "    def moverFicha(self, row: int, col: int, nCol: int):\n",
    "        ficha = self.getCelda(row, col)\n",
    "        if self.turno == 1: #la ficha es diferente para cada jugador\n",
    "            ficha = 'R'\n",
    "        else:\n",
    "            ficha = 'N'\n",
    "            \n",
    "        if self.contMovs == 2: # si me quedan 2 movs, estoy en mi 1er mov\n",
    "            numMov = 1\n",
    "        else:\n",
    "            numMov = 2\n",
    "        \n",
    "        #Obtengo la jugada \n",
    "        jugada = self.obtenerMov(row, col, self.turno, numMov)\n",
    "        #Pos final ficha\n",
    "        nRow = jugada[1][0]\n",
    "        \n",
    "        #Jugada\n",
    "        self.deleteTile(row, col)\n",
    "        self.contMovs -= 1\n",
    "        self.extraPerdida(nRow)\n",
    "        self.placeTile(nRow, nCol, ficha)\n",
    "            \n",
    "        #Cambio de turno   \n",
    "        if self.contMovs == 0:\n",
    "            self.contMovs = 2\n",
    "            if self.turnoExtra == False:\n",
    "                self.cambiarTurno()\n",
    "        return 0\n",
    "     \n",
    "    '''\n",
    "    Gestiona el turno extra y la pérdida de turno.\n",
    "\n",
    "    @param nRow: Fila de destino.\n",
    "    '''   \n",
    "    def extraPerdida(self, nRow):\n",
    "        #1er mov pierde turno\n",
    "        if self.contMovs == 1 and self.filaVacia(nRow):\n",
    "                self.contMovs = 0\n",
    "                self.turnoExtra = False\n",
    "                ##print(\"¡Fila de destino vacía! Pierdes el turno.\") ##la comenté por el minimax\n",
    "                \n",
    "        #turno extra en 2o mov\n",
    "        else: #añadí el else pq si no, tb me iba a este if de abajo\n",
    "            if self.contMovs == 0 and self.filaVacia(nRow):\n",
    "                if not self.turnoExtra:\n",
    "                    self.turnoExtra = True\n",
    "                    self.contMovs = 2\n",
    "                else:\n",
    "                    # El jugador ya tuvo un turno extra y no puede obtener otro consecutivo.\n",
    "                    self.turnoExtra = False\n",
    "\n",
    "            elif self.contMovs == 0 and self.turnoExtra == True:\n",
    "                self.turnoExtra = False\n",
    "        return \n",
    "        \n",
    "        \n",
    "    '''\n",
    "    Determina si se ha acabado la partida y qué jugador es el ganador.\n",
    "\n",
    "    @return: 1 si el jugador 1 gana, 2 si el jugador 2 gana, 0 en caso de empate, -1 si la partida no ha terminado.\n",
    "    '''\n",
    "    def endGame(self) -> int:\n",
    "        # Verificar si las fichas de ambos jugadores están separadas\n",
    "        fichas_separadas = True\n",
    "        filasR = [] #almacena los índices de las filas que contienen fichas rojas\n",
    "        filasN = [] #almacena los índices de las filas que contienen fichas negras\n",
    "        \n",
    "        #recorro las filas y añado el num de la fila en la lista correspondiente dependiendo de si hay fichas R o N\n",
    "        for i in range(self.fil):\n",
    "            if 'R' in self.matrix[i]:\n",
    "                filasR.append(i)\n",
    "            if 'N' in self.matrix[i]:\n",
    "                filasN.append(i)\n",
    "        \n",
    "        #Comprueba si la fila i está ocupada por fichas 'N'\n",
    "        for i in range(filasR[0], filasR[-1] + 1): \n",
    "            if i in filasN:\n",
    "                fichas_separadas = False\n",
    "                break\n",
    "                    \n",
    "        #compruebo que las filas ocupadas por las fichas 'N' estén separadas de las filas ocupadas por las fichas 'R'\n",
    "        if fichas_separadas and filasN and filasR:\n",
    "            if filasN[-1] < filasR[0] or filasR[-1] < filasN[0]:\n",
    "                fichas_separadas = True\n",
    "            else:\n",
    "                fichas_separadas = False\n",
    "        \n",
    "        #si las fichas están separadas, calculo la puntuación\n",
    "        if fichas_separadas:\n",
    "            puntosR = self.puntuaje(jugador=1)\n",
    "            puntosN = self.puntuaje(jugador=2)\n",
    "            print(\"Puntuación del jugador 1:\", puntosR)\n",
    "            print(\"Puntuación del jugador 2:\", puntosN)\n",
    "\n",
    "            if puntosR > puntosN:\n",
    "                print(\"El jugador 1 gana.\")\n",
    "                return 1\n",
    "            elif puntosR < puntosN:\n",
    "                print(\"El jugador 2 gana.\")\n",
    "                return 2\n",
    "            else:\n",
    "                print(\"La partida termina en empate.\")\n",
    "                return 0\n",
    "        else:\n",
    "            return -1  # Indica que la partida no ha terminado\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Función asociada al método *Minimax* (con poda $\\alpha-\\beta$)**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def miniMax(state:TableroLinja, currentLevel:int, maxLevel:int, player:int, alpha:int, beta:int, stop:bool) -> Tuple[TableroLinja, int, bool]:\n",
    "    # Defino los sucesores(hijos)\n",
    "    successorMatrices = [] #lista que almecenará los hijos (1 turno)\n",
    "    primerMov = [] #almacenará hijos con el 1er mov hecho\n",
    "    \n",
    "    if currentLevel == maxLevel:\n",
    "        return (state , state.utility(player), stop)  \n",
    "    \n",
    "    utility = state.utility(player) #LLamo a la función de utilidad\n",
    "    \n",
    "    #Actualizo el conjunto de las matrices de sucesores, coger los 5 primeros hijos q nos dé (un hijo = 2mov), o sea un turno\n",
    "    #padre = TableroLinja(state.getMatrix())\n",
    "    maxHijos = 4 #0-4 -> 5 hijos\n",
    "    for current_row in range(8):\n",
    "        for current_col in range(6):\n",
    "            child_state = TableroLinja(matrix = state.getMatrix())  # matriz padre turno siempre es 1 pq crea nueva inst\n",
    "            child_state.copyFrom(state) ##lo añado para que sea igual a state\n",
    "\n",
    "            if len(primerMov) == maxHijos:\n",
    "                break\n",
    "\n",
    "            jugada = child_state.obtenerMov(current_row, current_col, child_state.turno, child_state.queMovEs())\n",
    "            \n",
    "            if len(jugada) != 2: #si no hay una jugada posible (bien porque la fila destino está llena u otro motivo)\n",
    "                continue #salgo del bucle interior y continuo con el siguiente valor de current_row\n",
    "\n",
    "            nRow = jugada[1][0] #fila destino\n",
    "            newCol = child_state.celdasVacias(nRow) #lista con las col de las celdas vacías de nRow\n",
    "\n",
    "            if child_state.turno == player and newCol and child_state.validarMov(current_row, current_col, newCol[0]) and child_state.puedoHacerMov(\n",
    "                    current_row, current_col, newCol[0]): #solo se hace el mov si es válido\n",
    "                child_state.moverFicha(current_row, current_col, newCol[0])\n",
    "                primerMov.append(child_state)\n",
    "                \n",
    "    #genero hijos con los 2 mov\n",
    "    cont = 0\n",
    "    i = 0\n",
    "    for i in range(len(primerMov)): #recorro los estados del 1er mov #\n",
    "        for current_row in range(8):\n",
    "            for current_col in range(6):\n",
    "                \n",
    "                current_state = TableroLinja(primerMov[i].getMatrix())\n",
    "                current_state.copyFrom(primerMov[i])\n",
    "                \n",
    "                jugada = current_state.obtenerMov(current_row, current_col, current_state.turno, current_state.queMovEs())\n",
    "                \n",
    "                if len(jugada) != 2: #comprobamos que la fila no está ocupada\n",
    "                    continue #si lo está miramos en la siguiente current_col\n",
    "                    \n",
    "                nRow = jugada[1][0]\n",
    "                newCol = current_state.celdasVacias(nRow)\n",
    "     \n",
    "                if newCol and current_state.validarMov(current_row, current_col, newCol[0]) and current_state.puedoHacerMov(\n",
    "                            current_row, current_col, newCol[0]):  # Verificar si el movimiento es válido\n",
    "\n",
    "                    current_state.moverFicha(current_row, current_col, newCol[0])  # Realizar el segundo movimiento\n",
    "                    successorMatrices.append(current_state) # Agregar el sucesor a la lista\n",
    "                    cont+=1\n",
    "                    if cont == 4: #si ya hay 4 elmentos en successorMatrices, paramos de coger hijos\n",
    "                        break\n",
    "\n",
    "            if cont == 4: ##comprobar si son 4 o 5 hijos\n",
    "                break\n",
    "        if cont == 4:\n",
    "            break\n",
    "                   \n",
    "    if len(successorMatrices) == 0:\n",
    "        stopDigging = True\n",
    "        coste=state.utility(player)\n",
    "        return (state,coste,stopDigging)\n",
    "       \n",
    "    bestMatrix = None\n",
    "    \n",
    "    #si el jugador es la IA       \n",
    "    if player == 2:                    \n",
    "        maxValue = -math.inf #alpha (la mayor utilidad)\n",
    "        \n",
    "        for i in range(0, len(successorMatrices)):            \n",
    "            mat = TableroLinja(successorMatrices[i].getMatrix()) \n",
    "            mat.copyFrom(successorMatrices[i]) \n",
    "                \n",
    "            matrizS, utility, stop = miniMax(mat, currentLevel + 1, maxLevel, 1, alpha,beta,stop)\n",
    "            \n",
    "            best = utility #la mejor utilidad será la utilidad de la matriz del sucesor i \n",
    "            \n",
    "            if best > maxValue: #si la utilidad actual es mayor a la definida\n",
    "                maxValue = best\n",
    "                bestMatrix = TableroLinja(successorMatrices[i].getMatrix())  # la mejor matriz será la del sucesor i\n",
    "                bestMatrix.copyFrom(successorMatrices[i])  # copiar otros atributos necesarios\n",
    "                    \n",
    "            alpha = max(alpha, best)                \n",
    "            if best >= beta:\n",
    "                return (matrizS,best,stop)\n",
    "                \n",
    "    #si el jugador es el físico             \n",
    "    else:                           \n",
    "        minValue = math.inf #beta\n",
    "        \n",
    "        for i in range(0, len(successorMatrices)):\n",
    "            mat = TableroLinja(successorMatrices[i].getMatrix()) \n",
    "            mat.copyFrom(successorMatrices[i]) \n",
    "            matrizS, utility, stop = miniMax(mat, currentLevel + 1, maxLevel, 2, alpha,beta,stop)\n",
    "                \n",
    "            if utility < minValue:\n",
    "                minValue = utility\n",
    "                bestMatrix = TableroLinja(successorMatrices[i].getMatrix())  # mejor matriz será la del sucesor i\n",
    "                bestMatrix.copyFrom(successorMatrices[i])  # copiar otros atributos necesarios\n",
    "                \n",
    "            beta = min(beta, utility)\n",
    "            if utility <= alpha:                    \n",
    "                return (matrizS,utility,stop)\n",
    "                  \n",
    "    return (bestMatrix, maxValue if player == 2 else minValue, stop) #si el jugador es la IA se devuelve el valor máx      \n",
    "   "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Poner en funcionamiento Minimax**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def performActionMinMax(state:TableroLinja, player:int):\n",
    "    \n",
    "    tmp = TableroLinja(state.getMatrix())\n",
    "    tmp.copyFrom(state)\n",
    "    \n",
    "    depth = 2 #profundidad del árbol de los hijos creados\n",
    "    stop = False \n",
    "    currentLevel = 0\n",
    "    itera = 0  \n",
    "    \n",
    "    while not stop and itera <= depth:          \n",
    "        tmpMatrizB = TableroLinja(tmp.getMatrix())\n",
    "        tmpMatrizB.copyFrom(tmp) #para mantener los atributos\n",
    "        (matrizoptima, valoroptimo, stop) = miniMax(tmpMatrizB, currentLevel, depth, player , -math.inf, math.inf,stop);        \n",
    "        itera+=1      \n",
    "        \n",
    "    return matrizoptima"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Realización del movimiento por parte del jugador - ordenador**\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def AIAction(state:TableroLinja, player:int):\n",
    "    \n",
    "    global AIReadyToMove\n",
    "   \n",
    "    matriz = TableroLinja(state.getMatrix())\n",
    "    matriz.copyFrom(state)\n",
    "\n",
    "    movIa = performActionMinMax(matriz, player) #movimiento d la IA\n",
    "    \n",
    "    AIReadyToMove = False\n",
    "   \n",
    "    return movIa"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "matrizInicio=[['N','N','N','N','N','N'],\n",
    "              ['N','V','V','V','V','R'],\n",
    "              ['N','V','V','V','V','R'],\n",
    "              ['N','V','V','V','V','R'],\n",
    "              ['N','V','V','V','V','R'],\n",
    "              ['N','V','V','V','V','R'],\n",
    "              ['N','V','V','V','V','R'],\n",
    "              ['R','R','R','R','R','R']]\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Bienvenido al juego Linja, disfrute de la partida.\n",
      "\n",
      "\u001b[91mJugador 1 (R):\u001b[0m______\n",
      "Jugador 2 (N): IA\n",
      "\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAPoAAAFICAYAAAB5meP3AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8pXeV/AAAACXBIWXMAAA9hAAAPYQGoP6dpAABT00lEQVR4nO39bWxcZX7/j7+uc2bsufH4LmRZJ17nZm0SinNjshgKNCgsFJamhUbALhVatZX4ivYB4kFTleVBpa+EilQh8QC13a3UfVIBAkVILEFKvxH9/Xe7CZCUxElINovjOLZxbGKPx2OfmXN7Xf8H4zOZ3AAJPrN7HF8v6ZIn48nkfa6c9/lc9x+hlFJoNJobGuP3LUCj0dQfbXSNZhmgja7RLAO00TWaZYA2ukazDNBG12iWAdroGs0yQBtdo1kGaKNrNMuAxLV+UAhRTx0ajeYb8vrrr/PUU0995Weu2egA/+///T++/e1vx8b0+Xye7du3A/DLX/6Stra2WGibn5/nrrvuAuKlC3SdfRPiWmdjY2M8/PDDGMbXN8yvy+i33HILXV1d31hY1ExPT1df/8Ef/AErVqz4Paq5iGVZ1ddx0gW6zr4Jca2zTCZzzZ/VfXSNZhmgja7RLAOuq+m+GK5lN+zvq98TV21x1QXx1RZXXfD71VZXo8d5q3tctcVVF8RXW1x1QXy01c3otRdYKpU4f/48Y2NjTE1NYds26XSa9vZ2urq66OjoIJ1OX1Ep9Xq6xVVbXHXFWVtcdcVNW12MHootFoscOnSII0eOYFkWQgiklFiWRaFQoFgs0tDQQE9PDzt27OD2228nk8nUtWkVV21x1RVnbXHVFUdtkRo9vDilFKdPn2bv3r1ks1n6+/tpbGwkn88zPT2NZVmUSiWKxSITExMcPnyYkydPcscdd/DYY4+xfv16hBAopSK74Lhqi6uuOGuLq644a4s8oiulOHz4MO+//z73338/nZ2dHD16lFOnTjE9PU2pVCIIAoQQJBIJkskkK1euZGxsjAMHDuC6Lg8//DBbt26ty39CHLXFVVectcVVV1y1RWb08El24sQJ9uzZw65du2hubuadd97h9OnT5PN5bNsmCAKUUhiGgWmaNDQ0kM1mWbVqFcPDwxw6dAilFLlcju7u7htaW1x1xVlbXHXFXVskRg8vcHZ2ljfeeIPNmzeTy+V46623OHXqFLOzs3ieh5Sy+nQSQmAYBq7rUi6XSaVSdHR0MD4+zsDAAEopnnvuOXK53KKeaHHVFlddcdYWV11x1wYRGL22T3LgwAFmZmbYtGkTe/fu5cSJExQKheoFhhiGcYXocrmM7/u0tbUxMjJCsVikv7+fBx54YNGVHzdtcdUVZ21x1RV3bdV/b1F/u4b5+Xk++OAD7rzzTgYHBzl27Bizs7O4rovv+9USBEG16RKilEJKWf1sKpVifHyc9957D9u2b1htcdUVZ21x1RV3bZEZfXR0lOnpaTo7Ozl27BgzMzO4rksQBEgpkVISBAG+71/yZAOqzRgA3/cxTROAgYEBRkdHb1htcdUVZ21x1RV3bZEZ/ezZs6TTaaSUjI6O4jhOtT8SopSqlto+Su02u7BChBDk83kGBwdvWG1x1RVnbXHVFXdtkQ3GTUxMAJXmS7FYJAgC4OLKnrBPopTCNE0SiQSmaVZ/H/4u/D6lFI7jLPppFldtcdUVZ21x1RV3bRDh9Jpt27iuS6lUwnXdquDaJokQojqdkEwmq++HFxU2Z8Inmu/7zM3N3bDa4qorztriqivu2iIxuhCCVCpVXQhw+QWGzZPwKdbY2FhtqoT9l9onWe176XT6htQWV11x1hZXXXHXBhFG9JtuuqnaXAkHEsILCZ9iiUSCRCJxSROmtiIuH3kUQrB69eobVltcdcVZW1x1xV1bZINx3d3d+L7PF198QXNzc/X92qdZbTPl8idY+J7neTiOg+d5ZLNZenp6blhtcdUVZ21x1RV3bZEZvauri66uLo4ePcrNN98MXFxIEF5cSNj/CEvYVPF9n1KpVL3I2267jbVr196w2uKqK87a4qor7toiM3pTUxMPPvgg4+Pj5PN5WlpaqvOFtU+rcC6xdk7R8zxc18WyLMrlMo7j0NLSwuOPP35dB+AtNW1x1RVnbXHVFXdtizZ67WjiAw88QG9vLwMDA5UvNwwcx7lkNVDtRYXFtm3m5uawLAvbtjEMgx07dix66V9ctcVVV5y1xVVX3LWFRBLRQyEtLS08++yz3HzzzQwNDeE4TvUpVSqVsG0b27ZxHAfbtimXy8zNzTE7O1t9krmuS19fH8888wwtLS2XfP+NpC2uuuKsLa664q4NIj4FVghBb28vL7zwAp2dnRQKBcrlMuVyubqIYHZ2tloKhQJzc3OUSqVqJWzZsoXnn3+e3t7eKKXFVltcdcVZW1x1xVlbZEYPnziGYXDXXXfx8ssvc88996CUolwuV59k5XKZUqlUvfhSqcT8/Dye57F9+3b+7//9v9x9993XlH1iqWuLq644a4urrthrU+Gw4DVcxLlz5742U0vtdMHs7Cz79u1jz549nDx5sjrHGA5MGIZBOp3mD/7gD3jiiSfYuXMnra2tl/R5vorp6WluuukmAKampr42g8bvSptlWTQ1NcVOl66zG6vOzp49y/r163nzzTf54Q9/+JWa6mb02j/Pz88zODjI8ePHGRkZwbZtGhsbWbNmDb29vXR3d5PL5a64qHr9B9Rb2ze9aeutC3Sd3Uh19ns1+uVc7aJrv/Nq/861cr3/Ab8rbdd70/6udIGus+vVBfGts+sxet0ztVzv0/N3SVy1xVUXxFdbXHVBPLTp3GsazTJAG12jWQZoo2s0ywBtdI1mGXBdg3Hhmty4UKslXFIYB+KqC+KrLa66IL7aHMcBuOKgyatxXUbfu3cvra2t30hUPSiXy9XX7777biQncURB+B8A8dIFus6+CXGts8nJSQDy+fzXf1hdI4AuuugSw/Laa699rX91H12jWeK0t7d/7Weuq+l+6tQpOjs7Y7MYYXp6mjVr1gBw7tw52tvbY6HNsqzqCSNx0gW6zr4Jca2zoaEhNm/efE2bX67L6JlMprpMMQ7UDopks9lYaQuJmy5dZ9dPXOvsenToprtGswzQRtdolgF139QSci2b5OLQ79Fo6sVXeaDe935djX6NO2A1mhuWq3lAVX5xibnDz9XL8HUzeu0Flkolzp8/z9jYGFNTU9i2TTqdpr29na6uLjo6Okin01dUio7wmqWKQi04uvLas8rMjY4yP3wWb3KSoFTCzGRIfutmst9dR3Pnd0hmMlAnD9TF6KFhi8Uihw4d4siRI1iWhRACKSWWZVEoFCgWizQ0NNDT08OOHTu4/fbbyWQy2uCapYtaMDmVn3ahyOSv/gf71wdpnCmQQtLk+8i5ImpqCm9mlrl0mgu395H9s5186+4/JFUzmq4URGGHSI1ee1bW6dOn2bt3L9lslv7+fhobG8nn80xPT1ePvi0Wi0xMTHD48GFOnjzJHXfcwWOPPcb69esR4mJeKo1mqVA1uVRc+PRTpl9/m9Z0mtZ7/4hEKom8MIk/OYkoziHmLRryBZIjw2T2/Rflgx9x+uE/ZtWPn2bFLT0Y1Vt/8R6IPKIrpTh8+DDvv/8+999/P52dnRw9epRTp04xPT1dzTYphCCRSJBMJlm5ciVjY2McOHAA13V5+OGH2bp1qza7ZmkRNtWl4vyvD2K9/jar//QHJNevwTnwIaVPDiMnJgnmLfADhDAwkklEYxq5ehXmmTM0vfsLPi872D96gs47tiEEkXggMqOH0fzEiRPs2bOHXbt20dzczDvvvMPp06fJ5/PYtl09ATNMIdvQ0EA2m2XVqlUMDw9z6NAhlFLkcjm6u7ujkqfR1J0wmk8cPcr8z35Ox1//mGRbE/P/8XPcIwO4F6bwyzbKD0BV+t9GwsBsbMDM5UiuXUfw29Ok9+9jAmhoznHzxg2RaIvE6KHJZ2dneeONN9i8eTO5XI633nqLU6dOMTs7i+d51RxUtdklXdelXC6TSqXo6OhgfHycgYEBlFI899xz5HI5HdU1S4ZyoUD+tX9j1fe+R7I1R/Fffor9yVGcmQK+61W3lApAGALhGRiui1kqI9MZGrrWEIycI/PL/+aMIWj+xxdJR+CBRRu9tl9+4MABZmZm2LRpE3v37uXEiRMUCoWqyUNq08eGlMtlfN+nra2NkZERisUi/f39keWe0mjqRXW2SMHE/g/InJ8g/X+2UfzP1ykf+gQnnydwFgJd+JcMgVIGhlFp8UsFvmWh3AQN7StxPhtCzc9z9r57uXXnn8QnJdP8/DwffPABd955J4ODgxw7dozZ2dlqQvewhInmaqfSlLo0+XsqlWJ8fJz33nsvNpv8NZqvozw3h/XOXlq+fx/Op8dxPvy4EsltF+n7SD9AeT74ASq4mGEVQCy4Xbo+gR+QTKUJhs8y9NbbuHb5q//hayAyo4+OjjI9PU1nZyfHjh1jZmYG13Wr6WFrU8RefiJG2JQH8H0f0zQBGBgYYHR0NCqJGk3dUMDs2SESE5/TuG4dpY8+xp2aJnBclB8gA4mSAVJWAp1UC034akaWhbF1pZCej0gkSSgofPQxU8Mji9YXmdHPnj1LOp1GSsno6CiO41T75CHhE+zyfnrtNrvwoSCEIJ/PMzg4GJVEjaZuCBTW6c9Ip1KoIMAbHEKWbIQvEarye6r3v0QohcHF+19UnQ5KSpQEgcC5MMn53/xm0foiG4ybmJgAqGaMDIIAuDTxXDhdZpomiUQC0zQvyTFV299XSuE4jo7omqWBgvLYGG34yGIROVOAIEBVXI6g0h8PV74ZpkkimcBY8ICo/SIWzA44ts2FkcV7ILLpNdu2cV2XUqmE67qXrN2tNXM4pZZMJqvvh8YOm/RhVPd9n7m5uagkajR1QwF+2SJwbOR8Cel4lfXsAIZAYIAyMQ0QpkmysQGzIYlgIcAtfFYFEkMpPBngKYktYT4CD0RidCEEqVSquhjmcpOHTfQwkjc2Nlab62Efvjaa174Xl4P4NJqvRiAyTXiWhfI8kBf74EIYlWWshoFImBjJBA0NjRimCQqkDJBBALLSzK94wMeRkvmkiZnNLFpdZBH9pptuqjbZw8G00MxhJE8kEiQSiUua8bUPg8tH34UQrF69OiqJGk3dEAIavn0zdmEWJT1UMoFQYAgDEJU5c9PESJiIRAJhmghhVBbZVFu9AkXoAZt5JZlNplnR2blofZENxnV3d+P7Pl988QXNzc3V92sjem1T/fIoHr7neR6O4+B5Htlslp6enqgkajR1peXWW5nFwPt8HKOtrbq1xRALwS4MagBSolSloBRiofmuFjxgeQ5TQLmtjc6NGxetLTKjd3V10dXVxdGjR6uH/H3ZHtuwDx6WsLnu+z6lUqlq9Ntuu421a9dGJVGjqSut312HvWEDMwc/Irm6AymomJeLAc9UIGRlsE36PmqhyY5UqEDiex7l8jwF32PYMGjv28qq9WsXrS0yozc1NfHggw8yPj5OPp+npaWlOmdeG7HD+fTaeXXP83BdF8uyKJfLOI5DS0sLjz/+OJnM4vsnGk09CQNZuilH+65dTIx/jnvhAkZ7O4EfLETuyrSakqoSzYMAFor0AqTn4zkOpVKRgm1xTii+WNXBfU89RTq7+MMoF2302hH1Bx54gN7eXgYGBipfbhg4jnPJirhaY4fFtm3m5uawLAvbtjEMgx07dujlr5olhRCC7p2PUL77Xsb+9xC+oZCmgW+Xka6L9AOCwCfwfaTrVYrjEbg2brmENV+gUJpjVElONDfT/dAPuOuhh6rfvRgiG3VXStHS0sKzzz7Liy++yNDQEOl0umrsZDJ5xUBcOPDmOM4lP/v7+3nmmWdoaWmJ5CI1mnoT3tNN7W3c9g+7+XB4kNKnJ1nRmMF0bRJemUSyETPRgDCN6rSakhLPdSg7JYqBx4iSHE6lSN9zL3/+t39DLqIUaJHuRxdC0NvbywsvvMBLL73EmTNnqotiHMepmjyslNoo77ounufR19fH888/T29vb5TSNJrfGZ19W9jyz6/wq91/T/7YEVYGkoxSJB0bs7oKTiCVwpcBZSUpKhhB8EkqRe7ue/iLv9tNz+ZNkWmKzOiheQ3D4K677uLll1/m1Vdf5eDBg9i2jWmaV2SUqDW5EILt27eze/dutmzZck3ZJzSaOGIYBj3b76Hh3/+V/S/9E+f276dtvkiblKQDiUFlgU0AWMA0cFYYnMtm6Hng+/zlT37Chr6+SD0QeUQPzd7b28srr7zCvn372LNnDydPnqzOs4eDc4ZhkE6n2bZtG0888QQ7d+6ktbX1kn6/RrNUqNz/AJV7e92WrfzoZz/l0Hu/4MCbb3J84Bgqnyfh+0ipsA2wkkn8XAurN2/ir576IdsffZSW9hW1XxrBQVJ1PAVWCEFraytPPvkkjzzyCIODgxw/fpyRkRFs26axsZE1a9bQ29tLd3c3uVxOG1uz5Kkc/RT+AXJtrex4+mn6H3uUsd9+xpmBAcaHz1U8kErRsXYN3Zs28Z0Nt5DNNV/igSj9ELnRryYul8vR19dHX1/fJbvZrvZZbXbNUufy89qFEDTlmtm4bRsbt20D1MLprl9yr4vKzrUoqXumlssvRhtZs5y4+v0uIjnC+XrQI14azTJAG12jWQZoo2s0ywBtdI1mGXBdg3GFQoFsNlsvLddNPp+vvp6Zmfk9KrkUy7Kqr+OkC3SdfRPiWmfT09MAVxy2elXUNUJlMY8uuugSs/Laa699rX91012jWeK0t7d/7Weuq+l+6tQpOjs7YzMXPj09zZo1awA4d+4c7e3tsdBmWVb18I046QJdZ9+EuNbZ0NAQmzdvvqY18ddl9EwmQ1PT4jfBR0VtFpdsNhsrbSFx06Xr7PqJa51djw7ddNdolgHa6BrNMqDua91DajezfBlx6PdoNPXiqzxQ73u/rka/FnNrNDcyV/OAqvziil1uUD/D183otRdYKpU4f/48Y2NjTE1NYds26XSa9vZ2urq66OjoIJ1OX1EpOsJrlioKteDoymvPKjM3Osr88Fm8yUmCUgkzkyH5rZvJfncdzZ3fIZnJQJ08UBejh4YtFoscOnSII0eOYFkWQgiklFiWRaFQoFgs0tDQQE9PDzt27OD2228nk8log2uWLmrB5FR+2oUik7/6H+xfH6RxpkAKSZPvI+eKqKkpvJlZ5tJpLtzeR/bPdvKtu/+QVM1oemXf+uJlRWr02swrp0+fZu/evWSzWfr7+2lsbCSfzzM9PY1lWZRKJYrFIhMTExw+fJiTJ09yxx138Nhjj7F+/fpLUjZpNEuFqsml4sKnnzL9+tu0ptO03vtHJFJJ5IVJ/MlJRHEOMW/RkC+QHBkms++/KB/8iNMP/zGrfvw0K27pwaje+ov3QOQRXSnF4cOHef/997n//vvp7Ozk6NGjnDp1iunp6WoiRiEEiUSCZDLJypUrGRsb48CBA7iuy8MPP8zWrVu12TVLi7CpLhXnf30Q6/W3Wf2nPyC5fg3OgQ8pfXIYOTFJMG+BHyCEgZFMIhrTyNWrMM+coendX/B52cH+0RN03rFt4WiqxXsgMqOH0fzEiRPs2bOHXbt20dzczDvvvMPp06fJ5/PYtl09HDLMrtrQ0EA2m2XVqlUMDw9z6NAhlFLkcjm6u7ujkqfR1J0wmk8cPcr8z35Ox1//mGRbE/P/8XPcIwO4F6bwyzbKD0BV+t9GwsBsbMDM5UiuXUfw29Ok9+9jAmhoznHzxg2RaIvE6KHJZ2dneeONN9i8eTO5XI633nqLU6dOMTs7i+d51fRMtYkXXdelXC6TSqXo6OhgfHycgYEBlFI899xz5HI5HdU1S4ZyoUD+tX9j1fe+R7I1R/Fffor9yVGcmQK+61V3mgmoZFj1DAzXxSyVkekMDV1rCEbOkfnlf3PGEDT/44ukI/DAoo1e2y8/cOAAMzMzbNq0ib1793LixAkKhULV5CG1mVVDyuUyvu/T1tbGyMgIxWKR/v5+nZZJE3uqs0UKJvZ/QOb8BOn/s43if75O+dAnOPk8gbMQ6MK/ZAiUMjCMSotfKvAtC+UmaGhfifPZEGp+nrP33cutO/9k0R6IbGXc/Pw8H3zwAXfeeSeDg4McO3aM2dnZaq7zsITZWWqn0i7Pi55KpRgfH+e99967ZJ2xRhNnynNzWO/speX79+F8ehznw48rkdx2kb6P9AOU54MfoIKLyUcBxILbpesT+AHJVJpg+CxDb72Na5cXrS0yo4+OjjI9PU1nZyfHjh1jZmYG13WrmVNrs6devlE+bMoD+L6PaZoADAwMMDo6GpVEjaZuKGD27BCJic9pXLeO0kcf405NEzguyg+QgUTJACkrgU6qhSZ8NVnJwti6UkjPRySSJBQUPvqYqeGRReuLzOhnz54lnU4jpWR0dBTHcap98pDwCXZ5P712m134UBBCkM/nGRwcjEqiRlM3BArr9GekUylUEOANDiFLNsKXCFX5PdX7XyKUwuDi/S+qTgclJUpWznZ3Lkxy/je/WbS+yAbjJiYmgEoTPky9BBefWLVZVE3TJJFIVBMwhp+r7e8rpXAcR0d0zdJAQXlsjDZ8ZLGInClAEKAqLkdQ6Y+HK98M0ySRTGAseEDUfhELZgcc2+bCyOI9ENn0mm3buK5LqVTCdd1L1u7WmjmcUksmk9X3Q2OHTfowqvu+z9zcXFQSNZq6oQC/bBE4NnK+hHS8ynp2AEMgMECZmAYI0yTZ2IDZkKymTw4/qwKJoRSeDPCUxJYwH4EHIsuPnkqlqothLjd52EQPI3ljY2O1uR724Wujee176XQ6CokaTZ0RiEwTnmWhPA/kxT64EEZlGathIBImRjJBQ0MjhmmCAikDZBCArDTzKx7wcaRkPmliZjOLVhdZRL/pppuqTfZwMC00cxjJE4kEiUTikmZ87cPg8tF3IQSrV6+OSqJGUzeEgIZv34xdmEVJD5VMIBQYwgBEZc7cNDESJiKRQJgmQhiVRTbVVq9AEXrAZl5JZpNpVnR2LlpfZINx3d3d+L7PF198QXNzc/X92ohe21S/PIqH73meh+M4eJ5HNpulp6cnKokaTV1pufVWZjHwPh/HaGurbm0xxEKwC4MagJQoVSkohVhovqsFD1iewxRQbmujc+PGRWuLzOhdXV10dXVx9OjR6iF/X7bHNuyDhyVsrvu+T6lUqhr9tttuY+3atVFJ1GjqSut312Fv2MDMwY9Iru5ACirm5WLAMxUIWRlsk76PWmiyIxUqkPieR7k8T8H3GDYM2vu2smr92kVri8zoTU1NPPjgg4yPj5PP52lpaanOmddG7HA+vXZe3fM8XNfFsizK5TKO49DS0sLjjz9OJrP4/olGU0/CQJZuytG+axcT45/jXriA0d5O4AcLkbsyraakqkTzIICFIr0A6fl4jkOpVKRgW5wTii9WdXDfU0+Rzi7+MMpFG712RP2BBx6gt7eXgYGBypcbBo7jXLIirtbYYbFtm7m5OSzLwrZtDMNgx44devmrZkkhhKB75yOU776Xsf89hG8opGng22Wk6yL9gCDwCXwf6XqV4ngEro1bLmHNFyiU5hhVkhPNzXQ/9APueuih6ncvhshG3ZVStLS08Oyzz/Liiy8yNDREOp2uGjuZTF4xEBcOvDmOc8nP/v5+nnnmGVpaWiK5SI2m3oT3dFN7G7f9w24+HB6k9OlJVjRmMF2bhFcmkWzETDQgTKM6raakxHMdyk6JYuAxoiSHUynS99zLn//t35BrbY1EX6T70YUQ9Pb28sILL/DSSy9x5syZ6qIYx3GqJg8rpTbKu66L53n09fXx/PPP09vbG6U0jeZ3RmffFrb88yv8avffkz92hJWBJKMUScfGrK6CE0il8GVAWUmKCkYQfJJKkbv7Hv7i73bTs3lTZJoiM3poXsMwuOuuu3j55Zd59dVXOXjwILZtY5rmFRklak0uhGD79u3s3r2bLVu2XFP2CY0mjhiGQc/2e2j4939l/0v/xLn9+2mbL9ImJelAYlBZYBMAFjANnBUG57IZeh74Pn/5k5+woa8vUg9EHtFDs/f29vLKK6+wb98+9uzZw8mTJ6vz7OHgnGEYpNNptm3bxhNPPMHOnTtpbW29pN+v0SwVKvc/QOXeXrdlKz/62U859N4vOPDmmxwfOIbK50n4PlIqbAOsZBI/18LqzZv4q6d+yPZHH6WlfUXtl0ZwkFQdT4EVQtDa2sqTTz7JI488wuDgIMePH2dkZATbtmlsbGTNmjX09vbS3d1NLpfTxtYseSpHP4V/gFxbKzuefpr+xx5l7LefcWZggPHhcxUPpFJ0rF1D96ZNfGfDLWRzzZd4IEo/RG70q4nL5XL09fXR19d3yW62q31Wm12z1Ln8vHYhBE25ZjZu28bGbdsAtXC665fc66Kycy1K6p6p5fKL0UbWLCeufr+LSI5wvh70iJdGswzQRtdolgHa6BrNMkAbXaNZBlzXYFy4Lj0u1GpxHCc22uKqC+KrLa66IL7aHMcBuOKw1atxXUbfu3cvrRGtvY2CcvniMbjvvvtubE6jCf8DIF66QNfZNyGudTY5OQlAPp//+g+ra4TKqj1ddNElZuW11177Wv/qPrpGs8Rpb2//2s9cV9P91KlTdHZ2xmbRy/T0NGvWrAHg3LlztLe3x0KbZVnVU3bipAt0nX0T4lpnQ0NDbN68+Zo2v1yX0TOZDE1Niz/tIipqB0Wy2WystIXETZeus+snrnV2PTp0012jWQZoo2s0y4C6b2oJqd219mXEod+j0dSLr/JAve/9uhr9Wsyt0dzIXM0DqvKLK7azQv0MXzej115gqVTi/PnzjI2NMTU1hW3bpNNp2tvb6erqoqOjg3Q6fUWl6AivWaoo1IKjK689q8zc6Cjzw2fxJicJSiXMTIbkt24m+911NHd+h2QmA3XyQF2MHhq2WCxy6NAhjhw5gmVZCCGQUmJZFoVCgWKxSENDAz09PezYsYPbb7+dTCajDa5ZuqgFk1P5aReKTP7qf7B/fZDGmQIpJE2+j5wroqam8GZmmUunuXB7H9k/28m37v5DUjWj6ZUDKhYvK1Kj16ZYOn36NHv37iWbzdLf309jYyP5fJ7p6Wksy6JUKlEsFpmYmODw4cOcPHmSO+64g8cee4z169dfkptNo1kqVE0uFRc+/ZTp19+mNZ2m9d4/IpFKIi9M4k9OIopziHmLhnyB5MgwmX3/RfngR5x++I9Z9eOnWXFLD0b11l+8ByKP6EopDh8+zPvvv8/9999PZ2cnR48e5dSpU0xPT1czrgohSCQSJJNJVq5cydjYGAcOHMB1XR5++GG2bt2qza5ZWoRNdak4/+uDWK+/zeo//QHJ9WtwDnxI6ZPDyIlJgnkL/AAhDIxkEtGYRq5ehXnmDE3v/oLPyw72j56g845tC2fQLd4DkRk9jOYnTpxgz5497Nq1i+bmZt555x1Onz5NPp/Htu3qKbBhGuWGhgay2SyrVq1ieHiYQ4cOoZQil8vR3d0dlTyNpu6E0Xzi6FHmf/ZzOv76xyTbmpj/j5/jHhnAvTCFX7ZRfgCq0v82EgZmYwNmLkdy7TqC354mvX8fE0BDc46bN26IRFskRg9NPjs7yxtvvMHmzZvJ5XK89dZbnDp1itnZWTzPq+Zhq82w6rou5XKZVCpFR0cH4+PjDAwMoJTiueeeI5fL6aiuWTKUCwXyr/0bq773PZKtOYr/8lPsT47izBTwXa+6pVRAJZWyZ2C4LmapjExnaOhaQzByjswv/5szhqD5H18kHYEHFm302n75gQMHmJmZYdOmTezdu5cTJ05QKBSqJg+pTaEcUi6X8X2ftrY2RkZGKBaL9Pf36/xrmthTnS1SMLH/AzLnJ0j/n20U//N1yoc+wcnnCZyFQBf+JUOglIFhVFr8UoFvWSg3QUP7SpzPhlDz85y9715u3fkni/ZAZCvj5ufn+eCDD7jzzjsZHBzk2LFjzM7O4rouvu9XS5iGqXYqrTYPm+/7pFIpxsfHee+992KzyV+j+TrKc3NY7+yl5fv34Xx6HOfDjyuR3HaRvo/0A5Tngx+ggotZhgHEgtul6xP4AclUmmD4LENvvY1rl7/6H74GIjP66Ogo09PTdHZ2cuzYMWZmZnBdt5oiuTZN8uUnYoRNeQDf9zFNE4CBgQFGR0ejkqjR1A0FzJ4dIjHxOY3r1lH66GPcqWkCx0X5ATKQKBkgZSXQSbXQhK9mJVoYW1cK6fmIRJKEgsJHHzM1PLJofZEZ/ezZs6TTaaSUjI6O4jhOtU8eEj7BLu+n126zCx8KQgjy+TyDg4NRSdRo6oZAYZ3+jHQqhQoCvMEhZMlG+BKhKr+nev9LhFIYXLz/RdXpoKREyUoSB+fCJOd/85tF64tsMG5iYgKoNOHDHGtw8YlVmy7ZNE0SiUQ102r4udr+vlIKx3F0RNcsDRSUx8Zow0cWi8iZAgQBquJyBJX+eLjyzTBNEskExoIHRO0XsWB2wLFtLows3gORTa/Zto3rupRKJVzXvWTtbq2Zwym1ZDJZfT80dtikD6O67/vMzc1FJVGjqRsK8MsWgWMj50tIx6usZwcwBAIDlIlpgDBNko0NmA3Jap708LMqkBhK4ckAT0lsCfMReCASowshSKVS1cUwl5s8bKKHkbyxsbHaXA/78LXRvPa9uBzEp9F8NQKRacKzLJTngbzYBxfCqCxjNQxEwsRIJmhoaMQwTVAgZYAMApCVZn7FAz6OlMwnTcxsZtHqIovoN910U7XJHg6mhWYOI3kikSCRSFzSjK99GFw++i6EYPXq1VFJ1GjqhhDQ8O2bsQuzKOmhkgmEAkMYgKjMmZsmRsJEJBII00QIo7LIptrqFShCD9jMK8lsMs2Kzs5F64tsMK67uxvf9/niiy9obm6uvl8b0Wub6pdH8fA9z/NwHAfP88hms/T09EQlUaOpKy233sosBt7n4xhtbdWtLYZYCHZhUAOQEqUqBaUQC813teABy3OYAsptbXRu3LhobZEZvauri66uLo4ePVo95O/L9tiGffCwhM113/cplUpVo992222sXbs2KokaTV1p/e467A0bmDn4EcnVHUhBxbxcDHimAiErg23S91ELTXakQgUS3/Mol+cp+B7DhkF731ZWrV+7aG2RGb2pqYkHH3yQ8fFx8vk8LS0t1Tnz2ogdzqfXzqt7nofruliWRblcxnEcWlpaePzxx8lkFt8/0WjqSRjI0k052nftYmL8c9wLFzDa2wn8YCFyV6bVlFSVaB4EsFCkFyA9H89xKJWKFGyLc0LxxaoO7nvqKdLZxR9GuWij146oP/DAA/T29jIwMFD5csPAcZxLVsTVGjsstm0zNzeHZVnYto1hGOzYsUMvf9UsKYQQdO98hPLd9zL2v4fwDYU0DXy7jHRdpB8QBD6B7yNdr1Icj8C1ccslrPkChdIco0pyormZ7od+wF0PPVT97sUQ2ai7UoqWlhaeffZZXnzxRYaGhkin01VjJ5PJKwbiwoE3x3Eu+dnf388zzzxDS0tLJBep0dSb8J5uam/jtn/YzYfDg5Q+PcmKxgyma5PwyiSSjZiJBoRpVKfVlJR4rkPZKVEMPEaU5HAqRfqee/nzv/0bchGlQIt0P7oQgt7eXl544QVeeuklzpw5U10U4zhO1eRhpdRGedd18TyPvr4+nn/+eXp7e6OUptH8zujs28KWf36FX+3+e/LHjrAykGSUIunYmNVVcAKpFL4MKCtJUcEIgk9SKXJ338Nf/N1uejZvikxTZEYPzWsYBnfddRcvv/wyr776KgcPHsS2bUzTvCKjRK3JhRBs376d3bt3s2XLlmvKPqHRxBHDMOjZfg8N//6v7H/pnzi3fz9t80XapCQdSAwqC2wCwAKmgbPC4Fw2Q88D3+cvf/ITNvT1ReqByCN6aPbe3l5eeeUV9u3bx549ezh58mR1nj0cnDMMg3Q6zbZt23jiiSfYuXMnra2tl/T7NZqlQuX+B6jc2+u2bOVHP/sph977BQfefJPjA8dQ+TwJ30dKhW2AlUzi51pYvXkTf/XUD9n+6KO0tK+o/dIIDpKq4ymwQghaW1t58skneeSRRxgcHOT48eOMjIxg2zaNjY2sWbOG3t5euru7yeVy2tiaJU/l6KfwD5Bra2XH00/T/9ijjP32M84MDDA+fK7igVSKjrVr6N60ie9suIVsrvkSD0Tph8iNfjVxuVyOvr4++vr6LtnNdrXParNrljqXn9cuhKAp18zGbdvYuG0boBZOd/2Se11Udq5FSd0ztVx+MdrImuXE1e93EckRzteDHvHSaJYB2ugazTJAG12jWQZoo2s0y4DrGowrFApks9l6ablu8vl89fXMzMzvUcmlWJZVfR0nXaDr7JsQ1zqbnp4GuOKw1auirhEqi3l00UWXmJXXXnvta/2rm+4azRKnvb39az9zXU33U6dO0dnZGZu58OnpadasWQPAuXPnaG9vj4U2y7Kqh2/ESRfoOvsmxLXOhoaG2Lx58zWtib8uo2cyGZqaFr8JPipqs7hks9lYaQuJmy5dZ9dPXOvsenToprtGswzQRtdolgF1X+seUruZ5cuIQ79Ho6kXX+WBet/7dTX6tZhbo7mRuZoHVOUXV+xyg/oZvm5Gr73AUqnE+fPnGRsbY2pqCtu2SafTtLe309XVRUdHB+l0+opK0RFes1RRqAVHV157Vpm50VHmh8/iTU4SlEqYmQzJb91M9rvraO78DslMBurkgboYPTRssVjk0KFDHDlyBMuyEEIgpcSyLAqFAsVikYaGBnp6etixYwe33347mUxGG1yzdFELJqfy0y4UmfzV/2D/+iCNMwVSSJp8HzlXRE1N4c3MMpdOc+H2PrJ/tpNv3f2HpGpG0yv71hcvK1Kj12ZeOX36NHv37iWbzdLf309jYyP5fJ7p6Wksy6JUKlEsFpmYmODw4cOcPHmSO+64g8cee4z169dfkrJJo1kqVE0uFRc+/ZTp19+mNZ2m9d4/IpFKIi9M4k9OIopziHmLhnyB5MgwmX3/RfngR5x++I9Z9eOnWXFLD0b11l+8ByKP6EopDh8+zPvvv8/9999PZ2cnR48e5dSpU0xPT1cTMQohSCQSJJNJVq5cydjYGAcOHMB1XR5++GG2bt2qza5ZWoRNdak4/+uDWK+/zeo//QHJ9WtwDnxI6ZPDyIlJgnkL/AAhDIxkEtGYRq5ehXnmDE3v/oLPyw72j56g845tC0dTLd4DkRk9jOYnTpxgz5497Nq1i+bmZt555x1Onz5NPp/Htu3q4ZBhdtWGhgay2SyrVq1ieHiYQ4cOoZQil8vR3d0dlTyNpu6E0Xzi6FHmf/ZzOv76xyTbmpj/j5/jHhnAvTCFX7ZRfgCq0v82EgZmYwNmLkdy7TqC354mvX8fE0BDc46bN26IRFskRg9NPjs7yxtvvMHmzZvJ5XK89dZbnDp1itnZWTzPq6Znqk286Lou5XKZVCpFR0cH4+PjDAwMoJTiueeeI5fL6aiuWTKUCwXyr/0bq773PZKtOYr/8lPsT47izBTwXa+600xAJcOqZ2C4LmapjExnaOhaQzByjswv/5szhqD5H18kHYEHFm302n75gQMHmJmZYdOmTezdu5cTJ05QKBSqJg+pzawaUi6X8X2ftrY2RkZGKBaL9Pf367RMmthTnS1SMLH/AzLnJ0j/n20U//N1yoc+wcnnCZyFQBf+JUOglIFhVFr8UoFvWSg3QUP7SpzPhlDz85y9715u3fkni/ZAZCvj5ufn+eCDD7jzzjsZHBzk2LFjzM7OVnOdhyXMzlI7lXZ5XvRUKsX4+DjvvffeJeuMNZo4U56bw3pnLy3fvw/n0+M4H35cieS2i/R9pB+gPB/8ABVcTD4KIBbcLl2fwA9IptIEw2cZeuttXLu8aG2RGX10dJTp6Wk6Ozs5duwYMzMzuK5bzZxamz318o3yYVMewPd9TNMEYGBggNHR0agkajR1QwGzZ4dITHxO47p1lD76GHdqmsBxUX6ADCRKBkhZCXRSLTThq8lKFsbWlUJ6PiKRJKGg8NHHTA2PLFpfZEY/e/Ys6XQaKSWjo6M4jlPtk4eET7DL++m12+zCh4IQgnw+z+DgYFQSNZq6IVBYpz8jnUqhggBvcAhZshG+RKjK76ne/xKhFAYX739RdTooKVGycra7c2GS87/5zaL1RTYYNzExAVSa8GHqJbj4xKrNomqaJolEopqAMfxcbX9fKYXjODqia5YGCspjY7ThI4tF5EwBggBVcTmCSn88XPlmmCaJZAJjwQOi9otYMDvg2DYXRhbvgcim12zbxnVdSqUSrutesna31szhlFoymay+Hxo7bNKHUd33febm5qKSqNHUDQX4ZYvAsZHzJaTjVdazAxgCgQHKxDRAmCbJxgbMhmQ1fXL4WRVIDKXwZICnJLaE+Qg8EFl+9FQqVV0Mc7nJwyZ6GMkbGxurzfWwD18bzWvfS6fTUUjUaOqMQGSa8CwL5XkgL/bBhTAqy1gNA5EwMZIJGhoaMUwTFEgZIIMAZKWZX/GAjyMl80kTM5tZtLrIIvpNN91UbbKHg2mhmcNInkgkSCQSlzTjax8Gl4++CyFYvXp1VBI1mrohBDR8+2bswixKeqhkAqHAEAYgKnPmpomRMBGJBMI0EcKoLLKptnoFitADNvNKMptMs6Kzc9H6IhuM6+7uxvd9vvjiC5qbm6vv10b02qb65VE8fM/zPBzHwfM8stksPT09UUnUaOpKy623MouB9/k4RltbdWuLIRaCXRjUAKREqUpBKcRC810teMDyHKaAclsbnRs3LlpbZEbv6uqiq6uLo0ePVg/5+7I9tmEfPCxhc933fUqlUtXot912G2vXro1KokZTV1q/uw57wwZmDn5EcnUHUlAxLxcDnqlAyMpgm/R91EKTHalQgcT3PMrleQq+x7Bh0N63lVXr1y5aW2RGb2pq4sEHH2R8fJx8Pk9LS0t1zrw2Yofz6bXz6p7n4boulmVRLpdxHIeWlhYef/xxMpnF9080mnoSBrJ0U472XbuYGP8c98IFjPZ2Aj9YiNyVaTUlVSWaBwEsFOkFSM/HcxxKpSIF2+KcUHyxqoP7nnqKdHbxh1Eu2ui1I+oPPPAAvb29DAwMVL7cMHAc55IVcbXGDott28zNzWFZFrZtYxgGO3bs0MtfNUsKIQTdOx+hfPe9jP3vIXxDIU0D3y4jXRfpBwSBT+D7SNerFMcjcG3ccglrvkChNMeokpxobqb7oR9w10MPVb97MUQ26q6UoqWlhWeffZYXX3yRoaEh0ul01djJZPKKgbhw4M1xnEt+9vf388wzz9DS0hLJRWo09Sa8p5va27jtH3bz4fAgpU9PsqIxg+naJLwyiWQjZqIBYRrVaTUlJZ7rUHZKFAOPESU5nEqRvude/vxv/4Zca2sk+iLdjy6EoLe3lxdeeIGXXnqJM2fOVBfFOI5TNXlYKbVR3nVdPM+jr6+P559/nt7e3iilaTS/Mzr7trDln1/hV7v/nvyxI6wMJBmlSDo2ZnUVnEAqhS8DykpSVDCC4JNUitzd9/AXf7ebns2bItMUmdFD8xqGwV133cXLL7/Mq6++ysGDB7FtG9M0r8goUWtyIQTbt29n9+7dbNmy5ZqyT2g0ccQwDHq230PDv/8r+1/6J87t30/bfJE2KUkHEoPKApsAsIBp4KwwOJfN0PPA9/nLn/yEDX19kXog8ogemr23t5dXXnmFffv2sWfPHk6ePFmdZw8H5wzDIJ1Os23bNp544gl27txJa2vrJf1+jWapULn/ASr39rotW/nRz37Kofd+wYE33+T4wDFUPk/C95FSYRtgJZP4uRZWb97EXz31Q7Y/+igt7StqvzSCg6TqeAqsEILW1laefPJJHnnkEQYHBzl+/DgjIyPYtk1jYyNr1qyht7eX7u5ucrmcNrZmyVM5+in8A+TaWtnx9NP0P/YoY7/9jDMDA4wPn6t4IJWiY+0aujdt4jsbbiGba77EA1H6IXKjX01cLpejr6+Pvr6+S3azXe2z2uyapc7l57ULIWjKNbNx2zY2btsGqIXTXb/kXheVnWtRUvdMLZdfjDayZjlx9ftdRHKE8/WgR7w0mmWANrpGswzQRtdolgHa6BrNMuC6BuPCdelxoVaL4zix0RZXXRBfbXHVBfHV5jgOwBWHrV6N6zL63r17aY1o7W0UlMsXj8F99913Y3MaTfgfAPHSBbrOvglxrbPJyUkA8vn8139YXSNUVu3poosuMSuvvfba1/pX99E1miVOe3v7137muprup06dorOzMzaLXqanp1mzZg0A586do729PRbaLMuqnrITJ12g6+ybENc6GxoaYvPmzde0+eW6jJ7JZGhqWvxpF1FROyiSzWZjpS0kbrp0nV0/ca2z69Ghm+4azTJAG12jWQbUfVNLSO2utS8jDv0ejaZefJUH6n3v19Xo12JujeZG5moeUJVfXLGdFepn+LoZvfYCS6US58+fZ2xsjKmpKWzbJp1O097eTldXFx0dHaTT6SsqRUd4zVJFoRYcXXntWWXmRkeZHz6LNzlJUCphZjIkv3Uz2e+uo7nzOyQzGaiTB+pi9NCwxWKRQ4cOceTIESzLQgiBlBLLsigUChSLRRoaGujp6WHHjh3cfvvtZDIZbXDN0kUtmJzKT7tQZPJX/4P964M0zhRIIWnyfeRcETU1hTczy1w6zYXb+8j+2U6+dfcfkqoZTa8cULF4WZEavTbF0unTp9m7dy/ZbJb+/n4aGxvJ5/NMT09jWRalUoliscjExASHDx/m5MmT3HHHHTz22GOsX7/+ktxsGs1SoWpyqbjw6adMv/42rek0rff+EYlUEnlhEn9yElGcQ8xbNOQLJEeGyez7L8oHP+L0w3/Mqh8/zYpbejCqt/7iPRB5RFdKcfjwYd5//33uv/9+Ojs7OXr0KKdOnWJ6erqacVUIQSKRIJlMsnLlSsbGxjhw4ACu6/Lwww+zdetWbXbN0iJsqkvF+V8fxHr9bVb/6Q9Irl+Dc+BDSp8cRk5MEsxb4AcIYWAkk4jGNHL1KswzZ2h69xd8Xnawf/QEnXdsWziDbvEeiMzoYTQ/ceIEe/bsYdeuXTQ3N/POO+9w+vRp8vk8tm1XT4EN0yg3NDSQzWZZtWoVw8PDHDp0CKUUuVyO7u7uqORpNHUnjOYTR48y/7Of0/HXPybZ1sT8f/wc98gA7oUp/LKN8gNQlf63kTAwGxswczmSa9cR/PY06f37mAAamnPcvHFDJNoiMXpo8tnZWd544w02b95MLpfjrbfe4tSpU8zOzuJ5XjUPW22GVdd1KZfLpFIpOjo6GB8fZ2BgAKUUzz33HLlcTkd1zZKhXCiQf+3fWPW975FszVH8l59if3IUZ6aA73rVLaUCKqmUPQPDdTFLZWQ6Q0PXGoKRc2R++d+cMQTN//gi6Qg8sGij1/bLDxw4wMzMDJs2bWLv3r2cOHGCQqFQNXlIbQrlkHK5jO/7tLW1MTIyQrFYpL+/X+df08Se6myRgon9H5A5P0H6/2yj+J+vUz70CU4+T+AsBLrwLxkCpQwMo9Lilwp8y0K5CRraV+J8NoSan+fsffdy684/WbQHIlsZNz8/zwcffMCdd97J4OAgx44dY3Z2Ftd18X2/WsI0TLVTabV52HzfJ5VKMT4+znvvvRebTf4azddRnpvDemcvLd+/D+fT4zgfflyJ5LaL9H2kH6A8H/wAFVzMMgwgFtwuXZ/AD0im0gTDZxl6621cu/zV//A1EJnRR0dHmZ6eprOzk2PHjjEzM4PrutUUybVpki8/ESNsygP4vo9pmgAMDAwwOjoalUSNpm4oYPbsEImJz2lct47SRx/jTk0TOC7KD5CBRMkAKSuBTqqFJnw1K9HC2LpSSM9HJJIkFBQ++pip4ZFF64vM6GfPniWdTiOlZHR0FMdxqn3ykPAJdnk/vXabXfhQEEKQz+cZHByMSqJGUzcECuv0Z6RTKVQQ4A0OIUs2wpcIVfk91ftfIpTC4OL9L6pOByUlSlaSODgXJjn/m98sWl9kg3ETExNApQkf5liDi0+s2nTJpmmSSCSqmVbDz9X295VSOI6jI7pmaaCgPDZGGz6yWETOFCAIUBWXI6j0x8OVb4ZpkkgmMBY8IGq/iAWzA45tc2Fk8R6IbHrNtm1c16VUKuG67iVrd2vNHE6pJZPJ6vuhscMmfRjVfd9nbm4uKokaTd1QgF+2CBwbOV9COl5lPTuAIRAYoExMA4RpkmxswGxIVvOkh59VgcRQCk8GeEpiS5iPwAORGF0IQSqVqi6GudzkYRM9jOSNjY3V5nrYh6+N5rXvxeUgPo3mqxGITBOeZaE8D+TFPrgQRmUZq2EgEiZGMkFDQyOGaYICKQNkEICsNPMrHvBxpGQ+aWJmM4tWF1lEv+mmm6pN9nAwLTRzGMkTiQSJROKSZnztw+Dy0XchBKtXr45KokZTN4SAhm/fjF2YRUkPlUwgFBjCAERlztw0MRImIpFAmCZCGJVFNtVWr0AResBmXklmk2lWdHYuWl9kg3Hd3d34vs8XX3xBc3Nz9f3aiF7bVL88iofveZ6H4zh4nkc2m6WnpycqiRpNXWm59VZmMfA+H8doa6tubTHEQrALgxqAlChVKSiFWGi+qwUPWJ7DFFBua6Nz48ZFa4vM6F1dXXR1dXH06NHqIX9ftsc27IOHJWyu+75PqVSqGv22225j7dq1UUnUaOpK63fXYW/YwMzBj0iu7kAKKublYsAzFQhZGWyTvo9aaLIjFSqQ+J5HuTxPwfcYNgza+7ayav3aRWuLzOhNTU08+OCDjI+Pk8/naWlpqc6Z10bscD69dl7d8zxc18WyLMrlMo7j0NLSwuOPP04ms/j+iUZTT8JAlm7K0b5rFxPjn+NeuIDR3k7gBwuRuzKtpqSqRPMggIUivQDp+XiOQ6lUpGBbnBOKL1Z1cN9TT5HOLv4wykUbvXZE/YEHHqC3t5eBgYHKlxsGjuNcsiKu1thhsW2bubk5LMvCtm0Mw2DHjh16+atmSSGEoHvnI5Tvvpex/z2EbyikaeDbZaTrIv2AIPAJfB/pepXieASujVsuYc0XKJTmGFWSE83NdD/0A+566KHqdy+GyEbdlVK0tLTw7LPP8uKLLzI0NEQ6na4aO5lMXjEQFw68OY5zyc/+/n6eeeYZWlpaIrlIjabehPd0U3sbt/3Dbj4cHqT06UlWNGYwXZuEVyaRbMRMNCBMozqtpqTEcx3KToli4DGiJIdTKdL33Muf/+3fkIsoBVqk+9GFEPT29vLCCy/w0ksvcebMmeqiGMdxqiYPK6U2yruui+d59PX18fzzz9Pb2xulNI3md0Zn3xa2/PMr/Gr335M/doSVgSSjFEnHxqyughNIpfBlQFlJigpGEHySSpG7+x7+4u9207N5U2SaIjN6aF7DMLjrrrt4+eWXefXVVzl48CC2bWOa5hUZJWpNLoRg+/bt7N69my1btlxT9gmNJo4YhkHP9nto+Pd/Zf9L/8S5/ftpmy/SJiXpQGJQWWATABYwDZwVBueyGXoe+D5/+ZOfsKGvL1IPRB7RQ7P39vbyyiuvsG/fPvbs2cPJkyer8+zh4JxhGKTTabZt28YTTzzBzp07aW1tvaTfr9EsFSr3P0Dl3l63ZSs/+tlPOfTeLzjw5pscHziGyudJ+D5SKmwDrGQSP9fC6s2b+Kunfsj2Rx+lpX1F7ZdGcJBUHU+BFULQ2trKk08+ySOPPMLg4CDHjx9nZGQE27ZpbGxkzZo19Pb20t3dTS6X08bWLHkqRz+Ff4BcWys7nn6a/sceZey3n3FmYIDx4XMVD6RSdKxdQ/emTXxnwy1kc82XeCBKP0Ru9KuJy+Vy9PX10dfXd8lutqt9Vptds9S5/Lx2IQRNuWY2btvGxm3bALVwuuuX3OuisnMtSuqeqeXyi9FG1iwnrn6/i0iOcL4e9IiXRrMM0EbXaJYB2ugazTJAG12jWQZc12BcoVAgm83WS8t1k8/nq69nZmZ+j0ouxbKs6us46QJdZ9+EuNbZ9PQ0wBWHrV4VdY1QWcyjiy66xKy89tprX+tf3XTXaJYB19V0P3bsGKtWraqXlutmZmamegLN4OAgrRHt9FkslmWxZs0aIF66QNfZNyGudXb27FnuuOMO2tvbv/az12X0lpYW2tvbY7nopbW1NTbaUqlU9XWcdF1OnLTpOrt+isUiwDVtfrnupnscLvDLiKu2uOqC+GqLqy6It7YvQ/fRNZplgDa6RrMMqPumlpDaXWtfxlJsEmk018pXeaDe935djX4t5tZobmSu5gFV+cUV21mhfoavm9FrL7BUKnH+/HnGxsaYmprCtm3S6TTt7e10dXXR0dFBOp2+olJ0hNcsVRRqwdGV155VZm50lPnhs3iTkwSlEmYmQ/JbN5P97jqaO79DMpOBOnmgLkYPDVssFjl06BBHjhzBsiyEEEgpsSyLQqFAsVikoaGBnp4eduzYwe23304mk9EG1yxd1ILJqfy0C0Umf/U/2L8+SONMgRSSJt9HzhVRU1N4M7PMpdNcuL2P7J/t5Ft3/yGppovnuFcOqFi8rEiNXpti6fTp0+zdu5dsNkt/fz+NjY3k83mmp6exLItSqUSxWGRiYoLDhw9z8uRJ7rjjDh577DHWr19/SW42jWapUDW5VFz49FOmX3+b1nSa1nv/iEQqibwwiT85iSjOIeYtGvIFkiPDZPb9F+WDH3H64T9m1Y+fZsUtPRjVW3/xHog8oiulOHz4MO+//z73338/nZ2dHD16lFOnTjE9PV3NuCqEIJFIkEwmWblyJWNjYxw4cADXdXn44YfZunWrNrtmaRE21aXi/K8PYr3+Nqv/9Ack16/BOfAhpU8OIycmCeYt8AOEMDCSSURjGrl6FeaZMzS9+ws+LzvYP3qCzju2LZxBt3gPRGb0MJqfOHGCPXv2sGvXLpqbm3nnnXc4ffo0+Xwe27arp8CGaZQbGhrIZrOsWrWK4eFhDh06hFKKXC5Hd3d3VPI0mroTRvOJo0eZ/9nP6fjrH5Nsa2L+P36Oe2QA98IUftlG+QGoSv/bSBiYjQ2YuRzJtesIfnua9P59TAANzTlu3rghEm2RGD00+ezsLG+88QabN28ml8vx1ltvcerUKWZnZ/E8r5qHrTbDquu6lMtlUqkUHR0djI+PMzAwgFKK5557jlwup6O6ZslQLhTIv/ZvrPre90i25ij+y0+xPzmKM1PAd73qllIBlVTKnoHhupilMjKdoaFrDcHIOTK//G/OGILmf3yRdAQeWLTRa/vlBw4cYGZmhk2bNrF3715OnDhBoVComjykNoVySLlcxvd92traGBkZoVgs0t/fr/OvaWJPdbZIwcT+D8icnyD9f7ZR/M/XKR/6BCefJ3AWAl34lwyBUgaGUWnxSwW+ZaHcBA3tK3E+G0LNz3P2vnu5deefLNoDka2Mm5+f54MPPuDOO+9kcHCQY8eOMTs7i+u6+L5fLWEaptqptNo8bL7vk0qlGB8f57333sO27agkajR1pTw3h/XOXlq+fx/Op8dxPvy4EsltF+n7SD9AeT74ASq4mGUYQCy4Xbo+gR+QTKUJhs8y9NbbuHZ50doiM/ro6CjT09N0dnZy7NgxZmZmcF23miK5Nk3y5SdihE15AN/3MU0TgIGBAUZHR6OSqNHUDQXMnh0iMfE5jevWUfroY9ypaQLHRfkBMpAoGSBlJdBJtdCEr2YlWhhbVwrp+YhEkoSCwkcfMzU8smh9kRn97NmzpNNppJSMjo7iOE61Tx4SPsEu76fXbrMLHwpCCPL5PIODg1FJ1GjqhkBhnf6MdCqFCgK8wSFkyUb4EqEqv6d6/0uEUhhcvP9F1emgpETJShIH58Ik53/zm0Xri2wwbmJiAqg04cMca3DxiVWbLtk0TRKJRDXTavi52v6+UgrHcXRE1ywNFJTHxmjDRxaLyJkCBAGq4nIElf54uPLNME0SyQTGggdE7RexYHbAsW0ujCzeA5FNr9m2jeu6lEolXNe9ZO1urZnDKbVkMll9PzR22KQPo7rv+8zNzUUlUaOpGwrwyxaBYyPnS0jHq6xnBzAEAgOUiWmAME2SjQ2YDclqnvTwsyqQGErhyQBPSWwJ8xF4IBKjCyFIpVLVxTCXmzxsooeRvLGxsdpcD/vwtdG89r10Oh2FRI2mzghEpgnPslCeB/JiH1wIo7KM1TAQCRMjmaChoRHDNEGBlAEyCEBWmvkVD/g4UjKfNDGzmUWriyyi33TTTdUmeziYFpo5jOSJRIJEInFJM772YXD56LsQgtWrV0clUaOpG0JAw7dvxi7MoqSHSiYQCgxhAKIyZ26aGAkTkUggTBMhjMoim2qrV6AIPWAzrySzyTQrOjsXrS+ywbju7m583+eLL76gubm5+n5tRK9tql8excP3PM/DcRw8zyObzVYP5dNo4k7Lrbcyi4H3+ThGW1t1a4shFoJdGNQApESpSkEpxELzXS14wPIcpoByWxudGzcuWltkRu/q6qKrq4ujR49y8803A1++xzbsg4clbK77vk+pVKoa/bbbbmPt2rVRSdRo6krrd9dhb9jAzMGPSK7uQAoq5uViwDMVCFkZbJO+j1posiMVKpD4nke5PE/B9xg2DNr7trJq/dpFa4vM6E1NTTz44IOMj4+Tz+dpaWmpzpnXRuxwPr12Xt3zPFzXxbIsyuUyjuPQ0tLC448/Tiaz+P6JRlNPwkCWbsrRvmsXE+Of4164gNHeTuAHC5G7Mq2mpKpE8yCAhSK9AOn5eI5DqVSkYFucE4ovVnVw31NPkc42fY2Cr2fRRq8dUX/ggQfo7e1lYGCg8uWGgeM4l6yIqzV2WGzbZm5uDsuysG0bwzDYsWOHXv6qWVIIIeje+Qjlu+9l7H8P4RsKaRr4dhnpukg/IAh8At9Hul6lOB6Ba+OWS1jzBQqlOUaV5ERzM90P/YC7Hnqo+t2LIbJRd6UULS0tPPvss7z44osMDQ2RTqerxk4mk1cMxIUDb47jXPKzv7+fZ555hpaWlkguUqOpN+E93dTexm3/sJsPhwcpfXqSFY0ZTNcm4ZVJJBsxEw0I06hOqykp8VyHslOiGHiMKMnhVIr0Pffy53/7N+QiShYR6X50IQS9vb288MILvPTSS5w5c6a6KMZxnKrJw0qpjfKu6+J5Hn19fTz//PP09vZGKU2j+Z3R2beFLf/8Cr/a/ffkjx1hZSDJKEXSsTGrq+AEUil8GVBWkqKCEQSfpFLk7r6Hv/i73fRs3hSZpsiMHprXMAzuuusuXn75ZV599VUOHjyIbduYpnlFRolakwsh2L59O7t372bLli3XlH1Co4kjhmHQs/0eGv79X9n/0j9xbv9+2uaLtElJOpAYVBbYBIAFTANnhcG5bIaeB77PX/7kJ2zo64vUA5FH9NDsvb29vPLKK+zbt489e/Zw8uTJ6jx7ODhnGAbpdJpt27bxxBNPsHPnTlpbWy/p92s0S4XK/Q9QubfXbdnKj372Uw699wsOvPkmxweOofJ5Er6PlArbACuZxM+1sHrzJv7qqR+y/dFHaWlfUfulERwkVcdTYIUQtLa28uSTT/LII48wODjI8ePHGRkZwbZtGhsbWbNmDb29vXR3d5PL5bSxNUueytFP4R8g19bKjqefpv+xRxn77WecGRhgfPhcxQOpFB1r19C9aRPf2XAL2VzzJR6I0g+RG/1q4nK5HH19ffT19V2ym+1qn9Vm1yx1Lj+vXQhBU66Zjdu2sXHbNkAtnO76Jfe6qOxci5K6Z2q5/GK0kTXLiavf7yKSI5yvBz3ipdEsA7TRNZplgDa6RrMM0EbXaJYB1zUYVygUyGaz9dJy3eTz+errmZmZ36OSS7Esq/o6TrpA19k3Ia51Nj09DXDFYatXRV0jVBbz6KKLLjErr7322tf6VzfdNZolTnt7+9d+5rqa7qdOnaKzszM2c+HT09OsWbMGgHPnztHe3h4LbZZlVQ/fiJMu0HX2TYhrnQ0NDbF58+ZrWhN/XUbPZDI0NS1+E3xU1GZxyWazsdIWEjddus6un7jW2fXo0E13jWYZoI2u0SwD6r7WPaR2M8vl/L77O3HVFlddEF9tcdUFv19tdTX61S5MVX5xxQ4f+N3+R8RVW1x11f6bl7xX+YWusy8hLtrqYnSFWriaymvPKjM3Osr88Fm8yUmCUgkzkyH5rZvJfncdzZ3fIZnJwGWVUo+Ljqu2uOqKs7a46oqjtmiNrhYukMpPu1Bk8lf/g/3rgzTOFEghafJ95FwRNTWFNzPLXDrNhdv7yP7ZTr519x+SqhlJrOzZvcG1xVVXnLXFVVeMtUVq9OoFSsWFTz9l+vW3aU2nab33j0ikksgLk/iTk4jiHGLeoiFfIDkyTGbff1E++BGnH/5jVv34aVbc0oNRvbho/gfiqi2uuuKsLa664qwtOqOHzRSpOP/rg1ivv83qP/0ByfVrcA58SOmTw8iJSYJ5C/wAIQyMZBLRmEauXoV55gxN7/6Cz8sO9o+eoPOObQvH8qjFN1/iqi2uuuKsLa66Yq4tMqOHT7KJo0eZ/9nP6fjrH5Nsa2L+P36Oe2QA98IUftlG+QGoSt/DSBiYjQ2YuRzJtesIfnua9P59TAANzTlu3rjhhtYWV11x1hZXXXHXFmnTvVwokH/t31j1ve+RbM1R/JefYn9yFGemgO961V02AirZJT0Dw3UxS2VkOkND1xqCkXNkfvnfnDEEzf/4IulcLpInWly1xVVXnLXFVVectS16wUx4dDMKJvZ/QOb8BOk7t1H8z9cpH/oE+8IUvlVGOi7K8yslCJCBREmJCiTSD/AtC684T0P7SsRnQ6j33uXs//f/+8q5x6WqLa664qwtrrriri0kspVx5bk5rHf20vL9+3A+PY7z4ceVp5jtIn0f6Qcozwc/QAUXEy8CCAVIhXR9Aj8gmUoTDJ9l6K23ce3yDastrrrirC2uuuKuLRKjK2D27BCJic9pXLeO0kcf405NEzguyg+fXAFSVlIwSbXQfKkmalgYV1QK6fmIRJKEgsJHHzM1PHJDaourrjhri6uuuGuDiIwuUFinPyOdSqGCAG9wCFmyEb5EqMrvWXh6KSURSmEgMAyjmo8tnEFQUqJk5Vxr58Ik53/zmxtSW1x1xVlbXHXFXRtENRinoDw2Rhs+slhEzhQgCFCVK0RgYBhUV/0YpkkimcBYSMAoar+IhQsFHNvmwsjojaktrrrirC2uuuKujYiMrgC/bBE4NnK+hHQ8UKoi3hAIDFAmpgHCNEk2NmA2JKupY8PPqkBiKIUnAzwlsSXMz83dkNriqivO2uKqK+7aILLpNYHINOFZFsrzQF7sfwhhVJbwGQYiYWIkEzQ0NGKYJiiQMkAGAchKE0cpRRD4OFIynzQxs5kbVFtcdcVZW1x1xV1bREYXAhq+fTN2YRYlPVQygVBgCAMQlflC08RImIhEAmGaCGFUFhgs5Euv9GIUUkpc12ZeSWaTaVZ0dt6Q2uKqK87a4qor7togwum1lltvZRYD7/NxjLa26rJ+Q1SeaubCxQgAKVGqUlAKsdB0UVLieR6W5zAFlNva6Ny48YbVFlddcdYWV11x1xaZ0Vu/uw57wwZmDn5EcnUHUlARTth8EZgKhKwMNEi/smgAKUEqVCDxPY9yeZ6C7zFsGLT3bWXV+rU3rLa46oqztrjqiru2RRs9nAdMN+Vo37WLifHPcS9cwGhvJ/CDhadWZUpBSVV5kgUBLBTpBUjPx3McSqUiBdvinFB8saqD+556inT2mx/EF1dtcdUVZ21x1RV3bSGRRXQhBN07H6F8972M/e8hfEMhTQPfLiNdF+kHBIFP4PtI16sUxyNwbdxyCWu+QKE0x6iSnGhupvuhH3DXQw9Vv/tG1BZXXXHWFlddcdcW0WBcZYqgqb2N2/5hNx8OD1L69CQrGjOYrk3CK5NINmImGhCmUZ1SUFLiuQ5lp0Qx8BhRksOpFOl77uXP//ZvyLW23rDa4qorztriqivu2qAOR0l19m1hyz+/wq92/z35Y0dYGUgySpF0bMzqCiCBVApfBpSVpKhgBMEnqRS5u+/hL/5uNz2bN0UtLbba4qorztriqiuu2iI3umEY9Gy/h4Z//1f2v/RPnNu/n7b5Im1Skg4kBpXFBQFgAdPAWWFwLpuh54Hv85c/+Qkb+vquKfvEjaItrrrirC2uuuKqTahr3AMnhODcuXN0dXV96Wcq37TwdQrmCgUOvfcLDrz5JucHjqHyeRK+j5QK2wArmcTPtbB68ya+/9QP2f7oo7S0r6j9R/mqnsn09DQ33XQTAFNTU6xYseJLP/u71GZZVjWLRpx06Tq7sers7NmzrF+/njfffJMf/vCHX3EFERu9cqHqij9b83OM/fYzzgwMMD58Dtu2aUyl6Fi7hu5Nm/jOhlvI5povGXC4lsGH6/kP+F1qu56b9nepC3Sd3Uh1dj1Gj7zpfvlZ1UIImnLNbNy2jY3btgEKpb7iIkRl1049iKu2uOqKs7a46oqrtromcLj6hQgWOVMQCXHVFlddEF9tcdUF8dGmc69pNMsAbXSNZhmgja7RLAO00TWaZcB1DcYVCgWy2Wy9tFw3+Xy++npmZub3qORSLMuqvo6TLtB19k2Ia52FWsKz4r8SdY1QWQWgiy66xKy89tprX+vfa47o17iuRqPRxBDdR9dolgHa6BrNMkAbXaNZBmijazTLAG10jWYZoI2u0SwDtNE1mmWANrpGswzQRtdolgH/f1PFHnX4IYseAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 300x400 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "None\n",
      "--------------------------------------\n",
      "Turno extra: False\n",
      "ContMovs: 2\n",
      "--------------------------------------\n",
      "\n"
     ]
    }
   ],
   "source": [
    "salgo = False\n",
    "movimiento = 'NULL'\n",
    "print(\"Bienvenido al juego Linja, disfrute de la partida.\\n\")\n",
    "print(\"\\033[91mJugador 1 (R):\\033[0m______\\nJugador 2 (N): IA\\n\")\n",
    "\n",
    "tab = TableroLinja(matrizInicio)\n",
    "print(tab.imprimirTabConImagenes())\n",
    "\n",
    "while not salgo:\n",
    "    #print(tab.imprimirTabConImagenes())\n",
    "    print(\"--------------------------------------\")\n",
    "    print(f\"Turno extra: {tab.turnoExtra}\")\n",
    "    print(f\"ContMovs: {tab.contMovs}\")\n",
    "    print(\"--------------------------------------\")\n",
    "\n",
    "    if tab.turno == 1: # Verifica si es el turno del jugador humano (jugador 1)\n",
    "        print() #me aseguro de que el input salga después de los anteriores print\n",
    "        try:\n",
    "            movimiento = input(f\"\\033[91mjugador {tab.turno}:\\033[0m Introduce tu jugada (row, col, nCol): \")\n",
    "            fila, col, nCol = map(int, movimiento.split())\n",
    "\n",
    "            if tab.filaValida(fila) and tab.colValida(col) and tab.colValida(nCol) and tab.validarMovConPrints(fila, col, nCol) and tab.puedoHacerMovConPrints(fila, col, nCol) :\n",
    "                tab.moverFicha(fila, col, nCol)\n",
    "                print()\n",
    "                print(tab.imprimirTabConImagenes())\n",
    "                print()\n",
    "        except ValueError:\n",
    "            print()\n",
    "            print(\"\\033[1;91m******************************************************************\\033[0m\")\n",
    "            print(\"\\033[1;91mPor favor, introduce bien los datos separados por espacios.\\033[0m\")\n",
    "            print(\"\\033[1;91m******************************************************************\\033[0m\")\n",
    "            print(tab.imprimirTabConImagenes())\n",
    "    else:\n",
    "        # Actualiza directamente la matriz con el movimiento de la IA\n",
    "        print()\n",
    "        print(\"Jugador 2:\")\n",
    "        movIa = AIAction(tab,2)\n",
    "        tab.setMatrix(movIa.getMatrix())\n",
    "        tab.copyFrom(movIa)\n",
    "        print(tab.imprimirTabConImagenes())\n",
    "\n",
    "    if tab.endGame() != -1:\n",
    "        salgo = True\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
